using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace AppCondominio.Modules.Reservations.Infrastructure.Migrations;
[DbContext(typeof(ReservationsDbContext))][Migration("20260908172000_InitialReservations")]
public partial class InitialReservations:Migration
{
 protected override void Up(MigrationBuilder m){m.EnsureSchema("reservations");m.CreateTable(name:"Areas",schema:"reservations",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Code=t.Column<string>(type:"nvarchar(60)",maxLength:60,nullable:false),Name=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),Capacity=t.Column<int>(type:"int",nullable:false),Fee=t.Column<decimal>(type:"decimal(18,2)",nullable:false),IsActive=t.Column<bool>(type:"bit",nullable:false)},constraints:c=>c.PrimaryKey("PK_Areas",x=>x.Id));m.CreateIndex(name:"IX_Areas_CommunityId_Code",schema:"reservations",table:"Areas",columns:new[]{"CommunityId","Code"},unique:true);
 m.CreateTable(name:"Reservations",schema:"reservations",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),AreaId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),RequesterId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),StartsAt=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),EndsAt=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),Guests=t.Column<int>(type:"int",nullable:false),Fee=t.Column<decimal>(type:"decimal(18,2)",nullable:false),RequestedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),Status=t.Column<int>(type:"int",nullable:false),DecisionBy=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:true)},constraints:c=>c.PrimaryKey("PK_Reservations",x=>x.Id));m.CreateIndex(name:"IX_Reservations_AreaId_StartsAt_EndsAt",schema:"reservations",table:"Reservations",columns:new[]{"AreaId","StartsAt","EndsAt"});m.CreateIndex(name:"IX_Reservations_CommunityId_RequesterId",schema:"reservations",table:"Reservations",columns:new[]{"CommunityId","RequesterId"});}
 protected override void Down(MigrationBuilder m){m.DropTable(name:"Reservations",schema:"reservations");m.DropTable(name:"Areas",schema:"reservations");}
}