using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace AppCondominio.Modules.Governance.Infrastructure.Migrations;
[DbContext(typeof(GovernanceDbContext))][Migration("20260908173500_InitialGovernance")]
public partial class InitialGovernance:Migration
{
 protected override void Up(MigrationBuilder m){m.EnsureSchema("governance");m.CreateTable(name:"Assemblies",schema:"governance",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Title=t.Column<string>(type:"nvarchar(250)",maxLength:250,nullable:false),ScheduledAt=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),QuorumPercent=t.Column<decimal>(type:"decimal(5,2)",nullable:false),Status=t.Column<int>(type:"int",nullable:false),EligibleUnits=t.Column<int>(type:"int",nullable:false),PresentUnits=t.Column<int>(type:"int",nullable:false)},constraints:c=>c.PrimaryKey("PK_Assemblies",x=>x.Id));m.CreateIndex(name:"IX_Assemblies_CommunityId_ScheduledAt",schema:"governance",table:"Assemblies",columns:new[]{"CommunityId","ScheduledAt"});
 m.CreateTable(name:"Motions",schema:"governance",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),AssemblyId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Title=t.Column<string>(type:"nvarchar(300)",maxLength:300,nullable:false),Yes=t.Column<int>(type:"int",nullable:false),No=t.Column<int>(type:"int",nullable:false),Abstain=t.Column<int>(type:"int",nullable:false),IsClosed=t.Column<bool>(type:"bit",nullable:false)},constraints:c=>c.PrimaryKey("PK_Motions",x=>x.Id));m.CreateIndex(name:"IX_Motions_AssemblyId",schema:"governance",table:"Motions",column:"AssemblyId");
 m.CreateTable(name:"CoexistenceCases",schema:"governance",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),PropertyId=t.Column<Guid>(type:"uniqueidentifier",nullable:true),Category=t.Column<string>(type:"nvarchar(100)",maxLength:100,nullable:false),Description=t.Column<string>(type:"nvarchar(1200)",maxLength:1200,nullable:false),ReportedBy=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),ReportedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),Status=t.Column<int>(type:"int",nullable:false),Resolution=t.Column<string>(type:"nvarchar(1200)",maxLength:1200,nullable:true),PenaltyAmount=t.Column<decimal>(type:"decimal(18,2)",nullable:false),BillingReference=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:true)},constraints:c=>c.PrimaryKey("PK_CoexistenceCases",x=>x.Id));m.CreateIndex(name:"IX_CoexistenceCases_CommunityId_Status",schema:"governance",table:"CoexistenceCases",columns:new[]{"CommunityId","Status"});}
 protected override void Down(MigrationBuilder m){m.DropTable(name:"CoexistenceCases",schema:"governance");m.DropTable(name:"Motions",schema:"governance");m.DropTable(name:"Assemblies",schema:"governance");}
}