using AppCondominio.Modules.Maintenance.Application;
using AppCondominio.Modules.Maintenance.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
namespace AppCondominio.Modules.Maintenance.Infrastructure;
public sealed class MaintenanceDbContext(DbContextOptions<MaintenanceDbContext> options):DbContext(options){public DbSet<MaintenanceAsset> Assets=>Set<MaintenanceAsset>();public DbSet<PreventivePlan> PreventivePlans=>Set<PreventivePlan>();public DbSet<MaintenanceIncident> Incidents=>Set<MaintenanceIncident>();public DbSet<WorkOrder> WorkOrders=>Set<WorkOrder>();protected override void OnModelCreating(ModelBuilder modelBuilder)=>modelBuilder.ApplyConfigurationsFromAssembly(typeof(MaintenanceDbContext).Assembly);}
internal sealed class EfMaintenanceRepository(MaintenanceDbContext db):IMaintenanceRepository
{
 public async Task AddAsync<T>(T entity,CancellationToken ct) where T:class=>await db.Set<T>().AddAsync(entity,ct); public Task<MaintenanceAsset?> GetAssetAsync(Guid id,CancellationToken ct)=>db.Assets.FirstOrDefaultAsync(x=>x.Id==id,ct); public Task<PreventivePlan?> GetPlanAsync(Guid id,CancellationToken ct)=>db.PreventivePlans.FirstOrDefaultAsync(x=>x.Id==id,ct); public Task<MaintenanceIncident?> GetIncidentAsync(Guid id,CancellationToken ct)=>db.Incidents.FirstOrDefaultAsync(x=>x.Id==id,ct); public Task<WorkOrder?> GetWorkOrderAsync(Guid id,CancellationToken ct)=>db.WorkOrders.FirstOrDefaultAsync(x=>x.Id==id,ct); public Task<bool> AssetCodeExistsAsync(Guid communityId,string code,CancellationToken ct)=>db.Assets.AnyAsync(x=>x.CommunityId==communityId&&x.Code==code,ct); public Task<bool> WorkOrderNumberExistsAsync(Guid communityId,string number,CancellationToken ct)=>db.WorkOrders.AnyAsync(x=>x.CommunityId==communityId&&x.Number==number,ct); public async Task<MaintenanceKpi> GetKpiAsync(Guid communityId,DateOnly today,CancellationToken ct){var active=await db.Assets.CountAsync(x=>x.CommunityId==communityId&&x.Status==AssetStatus.Active,ct);var incidents=await db.Incidents.CountAsync(x=>x.CommunityId==communityId&&(x.Status==IncidentStatus.Open||x.Status==IncidentStatus.InProgress),ct);var due=await db.PreventivePlans.CountAsync(x=>x.CommunityId==communityId&&x.IsActive&&x.NextDueDate<=today,ct);var openOrders=await db.WorkOrders.CountAsync(x=>x.CommunityId==communityId&&x.Status!=WorkOrderStatus.Completed&&x.Status!=WorkOrderStatus.Cancelled,ct);var cost=await db.WorkOrders.Where(x=>x.CommunityId==communityId&&x.Status==WorkOrderStatus.Completed).SumAsync(x=>(decimal?)x.ActualCost,ct)??0;return new(active,incidents,due,openOrders,cost);} public Task SaveChangesAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
}
internal static class Map{public static void Apply<T>(EntityTypeBuilder<T>b,string table) where T:AppCondominio.SharedKernel.AggregateRoot{b.ToTable(table,"maintenance");b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Ignore(x=>x.DomainEvents);}}
internal sealed class AssetConfig:IEntityTypeConfiguration<MaintenanceAsset>{public void Configure(EntityTypeBuilder<MaintenanceAsset>b){Map.Apply(b,"Assets");b.Property(x=>x.Code).HasMaxLength(60).IsRequired();b.Property(x=>x.Name).HasMaxLength(200).IsRequired();b.Property(x=>x.Category).HasMaxLength(120).IsRequired();b.Property(x=>x.Location).HasMaxLength(200).IsRequired();b.HasIndex(x=>new{x.CommunityId,x.Code}).IsUnique();}}
internal sealed class PlanConfig:IEntityTypeConfiguration<PreventivePlan>{public void Configure(EntityTypeBuilder<PreventivePlan>b){Map.Apply(b,"PreventivePlans");b.Property(x=>x.Name).HasMaxLength(200).IsRequired();b.HasIndex(x=>new{x.CommunityId,x.AssetId,x.Name}).IsUnique();}}
internal sealed class IncidentConfig:IEntityTypeConfiguration<MaintenanceIncident>{public void Configure(EntityTypeBuilder<MaintenanceIncident>b){Map.Apply(b,"Incidents");b.Property(x=>x.Title).HasMaxLength(200).IsRequired();b.Property(x=>x.Description).HasMaxLength(1000).IsRequired();b.Property(x=>x.Priority).HasMaxLength(40).IsRequired();b.Property(x=>x.ReportedBy).HasMaxLength(200).IsRequired();b.HasIndex(x=>new{x.CommunityId,x.Status});}}
internal sealed class WorkOrderConfig:IEntityTypeConfiguration<WorkOrder>{public void Configure(EntityTypeBuilder<WorkOrder>b){Map.Apply(b,"WorkOrders");b.Property(x=>x.Number).HasMaxLength(60).IsRequired();b.Property(x=>x.Title).HasMaxLength(200).IsRequired();b.Property(x=>x.AssignedTo).HasMaxLength(200);b.Property(x=>x.ActualCost).HasPrecision(18,2);b.Property(x=>x.ProcurementReference).HasMaxLength(200);b.HasIndex(x=>new{x.CommunityId,x.Number}).IsUnique();}}
public static class DependencyInjection{public static IServiceCollection AddMaintenanceModule(this IServiceCollection services,IConfiguration configuration){var cs=configuration.GetConnectionString("Maintenance")??configuration.GetConnectionString("Procurement")??configuration.GetConnectionString("Organizations")??throw new InvalidOperationException("Maintenance connection string is required.");services.AddDbContext<MaintenanceDbContext>(o=>o.UseSqlServer(cs,sql=>sql.MigrationsHistoryTable("__EFMigrationsHistory","maintenance")));services.AddScoped<IMaintenanceRepository,EfMaintenanceRepository>();services.AddScoped<MaintenanceService>();return services;}}