using AppCondominio.Modules.SecurityOperations.Application;
using AppCondominio.Modules.SecurityOperations.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
namespace AppCondominio.Modules.SecurityOperations.Infrastructure;
public sealed class SecurityOperationsDbContext(DbContextOptions<SecurityOperationsDbContext> options):DbContext(options){public DbSet<VisitorAuthorization> Visits=>Set<VisitorAuthorization>();public DbSet<SecurityIncident> Incidents=>Set<SecurityIncident>();public DbSet<GuardAccessGrant> GuardAccessGrants=>Set<GuardAccessGrant>();protected override void OnModelCreating(ModelBuilder modelBuilder)=>modelBuilder.ApplyConfigurationsFromAssembly(typeof(SecurityOperationsDbContext).Assembly);}
internal sealed class EfSecurityOperationsRepository(SecurityOperationsDbContext db):ISecurityOperationsRepository
{
 public async Task AddAsync<T>(T entity,CancellationToken ct) where T:class=>await db.Set<T>().AddAsync(entity,ct);
 public Task<VisitorAuthorization?> GetVisitAsync(Guid id,CancellationToken ct)=>db.Visits.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<SecurityIncident?> GetIncidentAsync(Guid id,CancellationToken ct)=>db.Incidents.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<GuardAccessGrant?> GetGuardAccessAsync(Guid id,CancellationToken ct)=>db.GuardAccessGrants.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<GuardAccessGrant?> GetActiveGuardAccessByExternalUserAsync(string externalUserId,CancellationToken ct)=>db.GuardAccessGrants.Where(x=>x.ExternalUserId==externalUserId&&x.Status==GuardAccessStatus.Active).OrderByDescending(x=>x.StartsAtUtc).FirstOrDefaultAsync(ct);
 public Task<bool> HasActiveAuthorizationAsync(Guid communityId,string document,DateTimeOffset from,DateTimeOffset to,CancellationToken ct)=>db.Visits.AnyAsync(x=>x.CommunityId==communityId&&x.Document==document&&x.Status!=VisitStatus.Cancelled&&x.Status!=VisitStatus.CheckedOut&&x.ValidFrom<to&&x.ValidTo>from,ct);public Task<bool> GuardAccessExistsAsync(string externalUserId,CancellationToken ct)=>db.GuardAccessGrants.AnyAsync(x=>x.ExternalUserId==externalUserId&&x.Status==GuardAccessStatus.Active,ct);
 public async Task<IReadOnlyList<VisitorAuthorization>> GetCommunityVisitsAsync(Guid communityId,DateTimeOffset from,DateTimeOffset to,CancellationToken ct)=>await db.Visits.AsNoTracking().Where(x=>x.CommunityId==communityId&&x.ValidFrom<to&&x.ValidTo>from&&x.Status!=VisitStatus.Cancelled).OrderBy(x=>x.ValidFrom).ToArrayAsync(ct);
 public async Task<IReadOnlyList<SecurityIncident>> GetCommunityIncidentsAsync(Guid communityId,CancellationToken ct)=>await db.Incidents.AsNoTracking().Where(x=>x.CommunityId==communityId).OrderByDescending(x=>x.ReportedAtUtc).ToArrayAsync(ct);
 public async Task<SecurityOperationsKpi> GetKpiAsync(Guid communityId,CancellationToken ct){var active=await db.Visits.CountAsync(x=>x.CommunityId==communityId&&(x.Status==VisitStatus.Authorized||x.Status==VisitStatus.CheckedIn),ct);var checkedIn=await db.Visits.CountAsync(x=>x.CommunityId==communityId&&x.Status==VisitStatus.CheckedIn,ct);var open=await db.Incidents.CountAsync(x=>x.CommunityId==communityId&&x.Status==SecurityIncidentStatus.Open,ct);var escalated=await db.Incidents.CountAsync(x=>x.CommunityId==communityId&&x.Status==SecurityIncidentStatus.Escalated,ct);return new(active,checkedIn,open,escalated);}public Task SaveChangesAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
}
internal static class SecurityOperationsMap{public static void Apply<T>(EntityTypeBuilder<T>b,string table) where T:AppCondominio.SharedKernel.AggregateRoot{b.ToTable(table,"securityops");b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Ignore(x=>x.DomainEvents);}}
internal sealed class GuardAccessConfig:IEntityTypeConfiguration<GuardAccessGrant>{public void Configure(EntityTypeBuilder<GuardAccessGrant>b){SecurityOperationsMap.Apply(b,"GuardAccessGrants");b.Property(x=>x.ExternalUserId).HasMaxLength(200).IsRequired();b.Property(x=>x.DisplayName).HasMaxLength(200).IsRequired();b.Property(x=>x.RevocationReason).HasMaxLength(500);b.HasIndex(x=>new{x.ExternalUserId,x.Status}).IsUnique().HasFilter("[Status] = 1");b.HasIndex(x=>new{x.CommunityId,x.Status});}}
internal sealed class VisitConfig:IEntityTypeConfiguration<VisitorAuthorization>{public void Configure(EntityTypeBuilder<VisitorAuthorization>b){SecurityOperationsMap.Apply(b,"VisitorAuthorizations");b.Property(x=>x.VisitorName).HasMaxLength(200).IsRequired();b.Property(x=>x.Document).HasMaxLength(80).IsRequired();b.Property(x=>x.Destination).HasMaxLength(200).IsRequired();b.Property(x=>x.Gate).HasMaxLength(100);b.HasIndex(x=>new{x.CommunityId,x.Document,x.ValidFrom,x.ValidTo});}}
internal sealed class SecurityIncidentConfig:IEntityTypeConfiguration<SecurityIncident>{public void Configure(EntityTypeBuilder<SecurityIncident>b){SecurityOperationsMap.Apply(b,"SecurityIncidents");b.Property(x=>x.Type).HasMaxLength(100).IsRequired();b.Property(x=>x.Description).HasMaxLength(1000).IsRequired();b.Property(x=>x.Location).HasMaxLength(200).IsRequired();b.Property(x=>x.ReportedBy).HasMaxLength(200).IsRequired();b.Property(x=>x.Resolution).HasMaxLength(1000);b.HasIndex(x=>new{x.CommunityId,x.Status});}}
public static class DependencyInjection{public static IServiceCollection AddSecurityOperationsModule(this IServiceCollection services,IConfiguration configuration){var cs=configuration.GetConnectionString("SecurityOperations")??configuration.GetConnectionString("Reservations")??configuration.GetConnectionString("Organizations")??throw new InvalidOperationException("SecurityOperations connection string is required.");services.AddDbContext<SecurityOperationsDbContext>(o=>o.UseSqlServer(cs,sql=>sql.MigrationsHistoryTable("__EFMigrationsHistory","securityops")));services.AddScoped<ISecurityOperationsRepository,EfSecurityOperationsRepository>();services.AddScoped<SecurityOperationsService>();return services;}}