using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace AppCondominio.Modules.SecurityOperations.Infrastructure.Migrations;
[DbContext(typeof(SecurityOperationsDbContext))][Migration("20260908172500_InitialSecurityOperations")]
public partial class InitialSecurityOperations:Migration
{
 protected override void Up(MigrationBuilder m){m.EnsureSchema("securityops");m.CreateTable(name:"VisitorAuthorizations",schema:"securityops",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),HostPersonId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),VisitorName=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),Document=t.Column<string>(type:"nvarchar(80)",maxLength:80,nullable:false),Destination=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),ValidFrom=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),ValidTo=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),CreatedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),Status=t.Column<int>(type:"int",nullable:false),CheckedInAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:true),CheckedOutAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:true),Gate=t.Column<string>(type:"nvarchar(100)",maxLength:100,nullable:true)},constraints:c=>c.PrimaryKey("PK_VisitorAuthorizations",x=>x.Id));m.CreateIndex(name:"IX_VisitorAuthorizations_CommunityId_Document_ValidFrom_ValidTo",schema:"securityops",table:"VisitorAuthorizations",columns:new[]{"CommunityId","Document","ValidFrom","ValidTo"});
 m.CreateTable(name:"SecurityIncidents",schema:"securityops",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Type=t.Column<string>(type:"nvarchar(100)",maxLength:100,nullable:false),Description=t.Column<string>(type:"nvarchar(1000)",maxLength:1000,nullable:false),Location=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),ReportedBy=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),ReportedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),Status=t.Column<int>(type:"int",nullable:false),Resolution=t.Column<string>(type:"nvarchar(1000)",maxLength:1000,nullable:true)},constraints:c=>c.PrimaryKey("PK_SecurityIncidents",x=>x.Id));m.CreateIndex(name:"IX_SecurityIncidents_CommunityId_Status",schema:"securityops",table:"SecurityIncidents",columns:new[]{"CommunityId","Status"});}
 protected override void Down(MigrationBuilder m){m.DropTable(name:"SecurityIncidents",schema:"securityops");m.DropTable(name:"VisitorAuthorizations",schema:"securityops");}
}