<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Organizations persistence and adapters.</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Organizations.Application\Organizations.Application.csproj" />
  </ItemGroup>
</Project>
