using AppCondominio.Modules.Procurement.Application;
using AppCondominio.Modules.Procurement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace AppCondominio.Modules.Procurement.Infrastructure;

public sealed class ProcurementDbContext(DbContextOptions<ProcurementDbContext> options):DbContext(options)
{
    public DbSet<SupplierProfile> Suppliers=>Set<SupplierProfile>();public DbSet<SupplierAccessGrant> SupplierAccessGrants=>Set<SupplierAccessGrant>();public DbSet<PurchaseRequisition> Requisitions=>Set<PurchaseRequisition>();public DbSet<SourcingRound> Rounds=>Set<SourcingRound>();public DbSet<SupplierBid> Bids=>Set<SupplierBid>();public DbSet<PurchaseOrder> Orders=>Set<PurchaseOrder>();
    protected override void OnModelCreating(ModelBuilder modelBuilder)=>modelBuilder.ApplyConfigurationsFromAssembly(typeof(ProcurementDbContext).Assembly);
}

internal sealed class EfProcurementRepository(ProcurementDbContext db):IProcurementRepository
{
    public async Task AddAsync<T>(T entity,CancellationToken ct) where T:class=>await db.Set<T>().AddAsync(entity,ct);
    public Task<SupplierProfile?> GetSupplierAsync(Guid id,CancellationToken ct)=>db.Suppliers.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<PurchaseRequisition?> GetRequisitionAsync(Guid id,CancellationToken ct)=>db.Requisitions.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<SourcingRound?> GetRoundAsync(Guid id,CancellationToken ct)=>db.Rounds.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<SupplierBid?> GetBidAsync(Guid id,CancellationToken ct)=>db.Bids.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<PurchaseOrder?> GetOrderAsync(Guid id,CancellationToken ct)=>db.Orders.FirstOrDefaultAsync(x=>x.Id==id,ct);
    public Task<SupplierAccessGrant?> GetSupplierAccessAsync(Guid id,CancellationToken ct)=>db.SupplierAccessGrants.FirstOrDefaultAsync(x=>x.Id==id,ct);
    public Task<SupplierAccessGrant?> GetActiveSupplierAccessByExternalUserAsync(string externalUserId,CancellationToken ct)=>db.SupplierAccessGrants.Where(x=>x.ExternalUserId==externalUserId&&x.Status==SupplierAccessStatus.Active).OrderByDescending(x=>x.StartsAtUtc).FirstOrDefaultAsync(ct);
    public Task<bool> SupplierTaxIdExistsAsync(Guid communityId,string taxId,CancellationToken ct)=>db.Suppliers.AnyAsync(x=>x.CommunityId==communityId&&x.TaxId==taxId,ct);public Task<bool> RequisitionNumberExistsAsync(Guid communityId,string number,CancellationToken ct)=>db.Requisitions.AnyAsync(x=>x.CommunityId==communityId&&x.Number==number,ct);public Task<bool> BidExistsAsync(Guid roundId,Guid supplierId,CancellationToken ct)=>db.Bids.AnyAsync(x=>x.SourcingRoundId==roundId&&x.SupplierId==supplierId,ct);public Task<bool> OrderNumberExistsAsync(Guid communityId,string number,CancellationToken ct)=>db.Orders.AnyAsync(x=>x.CommunityId==communityId&&x.Number==number,ct);public Task<bool> SupplierAccessExistsAsync(Guid supplierId,string externalUserId,CancellationToken ct)=>db.SupplierAccessGrants.AnyAsync(x=>x.SupplierId==supplierId&&x.ExternalUserId==externalUserId&&x.Status==SupplierAccessStatus.Active,ct);
    public async Task<IReadOnlyList<SupplierProfile>> GetActiveSuppliersAsync(Guid communityId,CancellationToken ct)=>await db.Suppliers.AsNoTracking().Where(x=>x.CommunityId==communityId&&x.IsActive).OrderBy(x=>x.LegalName).ToArrayAsync(ct);
    public async Task<IReadOnlyList<SupplierBid>> GetBidsAsync(Guid roundId,CancellationToken ct)=>await db.Bids.Where(x=>x.SourcingRoundId==roundId).AsNoTracking().ToArrayAsync(ct);
    public async Task<IReadOnlyList<SourcingRound>> GetOpenRoundsAsync(Guid communityId,CancellationToken ct)=>await db.Rounds.AsNoTracking().Where(x=>x.CommunityId==communityId&&x.Status==SourcingRoundStatus.Open).OrderBy(x=>x.ClosesAtUtc).ToArrayAsync(ct);
    public async Task<IReadOnlyList<SupplierBid>> GetSupplierBidsAsync(Guid supplierId,CancellationToken ct)=>await db.Bids.AsNoTracking().Where(x=>x.SupplierId==supplierId).OrderByDescending(x=>x.SubmittedAtUtc).ToArrayAsync(ct);
    public async Task<IReadOnlyList<PurchaseOrder>> GetSupplierOrdersAsync(Guid supplierId,CancellationToken ct)=>await db.Orders.AsNoTracking().Where(x=>x.SupplierId==supplierId).OrderByDescending(x=>x.IssuedAtUtc).ToArrayAsync(ct);
    public Task SaveChangesAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);
}
internal static class ProcurementMap{public static void Apply<T>(EntityTypeBuilder<T>b,string table) where T:AppCondominio.SharedKernel.AggregateRoot{b.ToTable(table,"procurement");b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Ignore(x=>x.DomainEvents);}}
internal sealed class SupplierConfig:IEntityTypeConfiguration<SupplierProfile>{public void Configure(EntityTypeBuilder<SupplierProfile>b){ProcurementMap.Apply(b,"Suppliers");b.Property(x=>x.TaxId).HasMaxLength(40).IsRequired();b.Property(x=>x.LegalName).HasMaxLength(200).IsRequired();b.Property(x=>x.Email).HasMaxLength(200).IsRequired();b.HasIndex(x=>new{x.CommunityId,x.TaxId}).IsUnique();}}
internal sealed class SupplierAccessConfig:IEntityTypeConfiguration<SupplierAccessGrant>{public void Configure(EntityTypeBuilder<SupplierAccessGrant>b){ProcurementMap.Apply(b,"SupplierAccessGrants");b.Property(x=>x.ExternalUserId).HasMaxLength(200).IsRequired();b.Property(x=>x.RevocationReason).HasMaxLength(500);b.HasIndex(x=>new{x.ExternalUserId,x.Status}).IsUnique().HasFilter("[Status] = 1");b.HasIndex(x=>new{x.SupplierId,x.ExternalUserId,x.Status});}}
internal sealed class RequisitionConfig:IEntityTypeConfiguration<PurchaseRequisition>{public void Configure(EntityTypeBuilder<PurchaseRequisition>b){ProcurementMap.Apply(b,"Requisitions");b.Property(x=>x.Number).HasMaxLength(60).IsRequired();b.Property(x=>x.Description).HasMaxLength(800).IsRequired();b.Property(x=>x.EstimatedAmount).HasPrecision(18,2);b.Property(x=>x.RequestedBy).HasMaxLength(200).IsRequired();b.Property(x=>x.ApprovedBy).HasMaxLength(200);b.HasIndex(x=>new{x.CommunityId,x.Number}).IsUnique();}}
internal sealed class RoundConfig:IEntityTypeConfiguration<SourcingRound>{public void Configure(EntityTypeBuilder<SourcingRound>b){ProcurementMap.Apply(b,"SourcingRounds");b.Property(x=>x.Title).HasMaxLength(200).IsRequired();b.HasIndex(x=>x.RequisitionId);}}
internal sealed class BidConfig:IEntityTypeConfiguration<SupplierBid>{public void Configure(EntityTypeBuilder<SupplierBid>b){ProcurementMap.Apply(b,"SupplierBids");b.Property(x=>x.Amount).HasPrecision(18,2);b.Property(x=>x.EvaluationScore).HasPrecision(5,2);b.Property(x=>x.ProposalReference).HasMaxLength(500).IsRequired();b.HasIndex(x=>new{x.SourcingRoundId,x.SupplierId}).IsUnique();}}
internal sealed class OrderConfig:IEntityTypeConfiguration<PurchaseOrder>{public void Configure(EntityTypeBuilder<PurchaseOrder>b){ProcurementMap.Apply(b,"PurchaseOrders");b.Property(x=>x.Number).HasMaxLength(60).IsRequired();b.Property(x=>x.Amount).HasPrecision(18,2);b.Property(x=>x.PayableReference).HasMaxLength(200).IsRequired();b.HasIndex(x=>new{x.CommunityId,x.Number}).IsUnique();b.HasIndex(x=>x.AwardedBidId).IsUnique();}}
public static class DependencyInjection{public static IServiceCollection AddProcurementModule(this IServiceCollection services,IConfiguration configuration){var cs=configuration.GetConnectionString("Procurement")??configuration.GetConnectionString("Budgeting")??configuration.GetConnectionString("Organizations")??throw new InvalidOperationException("Procurement connection string is required.");services.AddDbContext<ProcurementDbContext>(o=>o.UseSqlServer(cs,sql=>sql.MigrationsHistoryTable("__EFMigrationsHistory","procurement")));services.AddScoped<IProcurementRepository,EfProcurementRepository>();services.AddScoped<ProcurementService>();return services;}}