<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>AppCondominio.Api</AssemblyName>
    <RootNamespace>AppCondominio.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AppCondominio.Bootstrapper\AppCondominio.Bootstrapper.csproj" />
    <ProjectReference Include="..\AppCondominio.Contracts\AppCondominio.Contracts.csproj" />
    <ProjectReference Include="..\AppCondominio.Infrastructure\AppCondominio.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Organizations\Organizations.Api\Organizations.Api.csproj" />
  </ItemGroup>
</Project>
