using AppCondominio.Modules.SecurityOperations.Domain;
namespace AppCondominio.Modules.SecurityOperations.Application;
public interface ISecurityOperationsRepository
{
 Task AddAsync<T>(T entity,CancellationToken ct) where T:class;
 Task<VisitorAuthorization?> GetVisitAsync(Guid id,CancellationToken ct);Task<SecurityIncident?> GetIncidentAsync(Guid id,CancellationToken ct);Task<GuardAccessGrant?> GetGuardAccessAsync(Guid id,CancellationToken ct);Task<GuardAccessGrant?> GetActiveGuardAccessByExternalUserAsync(string externalUserId,CancellationToken ct);
 Task<bool> HasActiveAuthorizationAsync(Guid communityId,string document,DateTimeOffset from,DateTimeOffset to,CancellationToken ct);Task<bool> GuardAccessExistsAsync(string externalUserId,CancellationToken ct);
 Task<IReadOnlyList<VisitorAuthorization>> GetCommunityVisitsAsync(Guid communityId,DateTimeOffset from,DateTimeOffset to,CancellationToken ct);Task<IReadOnlyList<SecurityIncident>> GetCommunityIncidentsAsync(Guid communityId,CancellationToken ct);Task<SecurityOperationsKpi> GetKpiAsync(Guid communityId,CancellationToken ct);Task SaveChangesAsync(CancellationToken ct);
}
public sealed record GuardPortalContext(Guid CommunityId,string DisplayName);
public sealed record GuardVisitRow(Guid Id,string VisitorName,string Document,string Destination,DateTimeOffset ValidFrom,DateTimeOffset ValidTo,VisitStatus Status,DateTimeOffset? CheckedInAtUtc,DateTimeOffset? CheckedOutAtUtc,string? Gate);
public sealed record GuardIncidentRow(Guid Id,string Type,string Description,string Location,string ReportedBy,DateTimeOffset ReportedAtUtc,SecurityIncidentStatus Status,string? Resolution);
public sealed class SecurityOperationsService(ISecurityOperationsRepository repository)
{
 public async Task<Guid> GrantGuardPortalAccessAsync(Guid communityId,string externalUserId,string displayName,DateTimeOffset? expiresAtUtc,CancellationToken ct){if(communityId==Guid.Empty)throw new ArgumentException("Community required.",nameof(communityId));var userId=string.IsNullOrWhiteSpace(externalUserId)?throw new ArgumentException("External user required.",nameof(externalUserId)):externalUserId.Trim();var existing=await repository.GetActiveGuardAccessByExternalUserAsync(userId,ct);if(existing is not null&&existing.IsUsable(DateTimeOffset.UtcNow))throw new InvalidOperationException("Portal user already has active guard access.");if(await repository.GuardAccessExistsAsync(userId,ct))throw new InvalidOperationException("Portal user already has active guard access.");var grant=GuardAccessGrant.Create(communityId,userId,displayName,DateTimeOffset.UtcNow,expiresAtUtc);await repository.AddAsync(grant,ct);await repository.SaveChangesAsync(ct);return grant.Id;}
 public async Task RevokeGuardPortalAccessAsync(Guid id,string reason,CancellationToken ct){var access=await repository.GetGuardAccessAsync(id,ct)??throw new KeyNotFoundException("Guard access not found.");access.Revoke(reason);await repository.SaveChangesAsync(ct);}
 public async Task<GuardPortalContext> GetGuardPortalContextAsync(string externalUserId,CancellationToken ct){if(string.IsNullOrWhiteSpace(externalUserId))throw new UnauthorizedAccessException("Authenticated Portal user is required.");var access=await repository.GetActiveGuardAccessByExternalUserAsync(externalUserId.Trim(),ct)??throw new UnauthorizedAccessException("Guard access was not found for the authenticated user.");if(!access.IsUsable(DateTimeOffset.UtcNow))throw new UnauthorizedAccessException("Guard access is expired or revoked.");return new(access.CommunityId,access.DisplayName);}
 public async Task<IReadOnlyList<GuardVisitRow>> GetGuardVisitsAsync(string externalUserId,DateTimeOffset? from,DateTimeOffset? to,CancellationToken ct){var current=await GetGuardPortalContextAsync(externalUserId,ct);var start=from??DateTimeOffset.UtcNow.AddHours(-12);var end=to??DateTimeOffset.UtcNow.AddDays(1);if(end<=start)throw new ArgumentException("Invalid visit range.");return (await repository.GetCommunityVisitsAsync(current.CommunityId,start,end,ct)).Select(x=>new GuardVisitRow(x.Id,x.VisitorName,x.Document,x.Destination,x.ValidFrom,x.ValidTo,x.Status,x.CheckedInAtUtc,x.CheckedOutAtUtc,x.Gate)).OrderBy(x=>x.ValidFrom).ToArray();}
 public async Task<IReadOnlyList<GuardIncidentRow>> GetGuardIncidentsAsync(string externalUserId,CancellationToken ct){var current=await GetGuardPortalContextAsync(externalUserId,ct);return (await repository.GetCommunityIncidentsAsync(current.CommunityId,ct)).Where(x=>x.Status!=SecurityIncidentStatus.Resolved).Select(x=>new GuardIncidentRow(x.Id,x.Type,x.Description,x.Location,x.ReportedBy,x.ReportedAtUtc,x.Status,x.Resolution)).OrderByDescending(x=>x.ReportedAtUtc).ToArray();}
 public async Task CheckInForGuardAsync(string externalUserId,Guid visitId,DateTimeOffset at,string gate,CancellationToken ct){var current=await GetGuardPortalContextAsync(externalUserId,ct);var visit=await repository.GetVisitAsync(visitId,ct)??throw new KeyNotFoundException("Visitor authorization not found.");if(visit.CommunityId!=current.CommunityId)throw new UnauthorizedAccessException("Visitor authorization does not belong to the guard community.");visit.CheckIn(at,gate);await repository.SaveChangesAsync(ct);}
 public async Task CheckOutForGuardAsync(string externalUserId,Guid visitId,DateTimeOffset at,CancellationToken ct){var current=await GetGuardPortalContextAsync(externalUserId,ct);var visit=await repository.GetVisitAsync(visitId,ct)??throw new KeyNotFoundException("Visitor authorization not found.");if(visit.CommunityId!=current.CommunityId)throw new UnauthorizedAccessException("Visitor authorization does not belong to the guard community.");visit.CheckOut(at);await repository.SaveChangesAsync(ct);}
 public async Task<Guid> ReportGuardIncidentAsync(string externalUserId,string type,string description,string location,CancellationToken ct){var current=await GetGuardPortalContextAsync(externalUserId,ct);return await ReportIncidentAsync(current.CommunityId,type,description,location,current.DisplayName,ct);}
 public async Task<Guid> AuthorizeVisitAsync(Guid communityId,Guid hostPersonId,string visitorName,string document,string destination,DateTimeOffset validFrom,DateTimeOffset validTo,CancellationToken ct){if(await repository.HasActiveAuthorizationAsync(communityId,document,validFrom,validTo,ct))throw new InvalidOperationException("Visitor already has an overlapping authorization.");var x=VisitorAuthorization.Create(communityId,hostPersonId,visitorName,document,destination,validFrom,validTo);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
 public async Task CheckInAsync(Guid id,DateTimeOffset at,string gate,CancellationToken ct){var x=await repository.GetVisitAsync(id,ct)??throw new KeyNotFoundException("Visitor authorization not found.");x.CheckIn(at,gate);await repository.SaveChangesAsync(ct);} public async Task CheckOutAsync(Guid id,DateTimeOffset at,CancellationToken ct){var x=await repository.GetVisitAsync(id,ct)??throw new KeyNotFoundException("Visitor authorization not found.");x.CheckOut(at);await repository.SaveChangesAsync(ct);} public async Task CancelVisitAsync(Guid id,CancellationToken ct){var x=await repository.GetVisitAsync(id,ct)??throw new KeyNotFoundException("Visitor authorization not found.");x.Cancel();await repository.SaveChangesAsync(ct);}
 public async Task<Guid> ReportIncidentAsync(Guid communityId,string type,string description,string location,string reportedBy,CancellationToken ct){var x=SecurityIncident.Create(communityId,type,description,location,reportedBy);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;} public async Task EscalateIncidentAsync(Guid id,CancellationToken ct){var x=await repository.GetIncidentAsync(id,ct)??throw new KeyNotFoundException("Security incident not found.");x.Escalate();await repository.SaveChangesAsync(ct);} public async Task ResolveIncidentAsync(Guid id,string resolution,CancellationToken ct){var x=await repository.GetIncidentAsync(id,ct)??throw new KeyNotFoundException("Security incident not found.");x.Resolve(resolution);await repository.SaveChangesAsync(ct);} public Task<SecurityOperationsKpi> GetKpiAsync(Guid communityId,CancellationToken ct)=>repository.GetKpiAsync(communityId,ct);
}