using AppCondominio.Modules.Reservations.Application;
using AppCondominio.Modules.Reservations.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
namespace AppCondominio.Modules.Reservations.Infrastructure;
public sealed class ReservationsDbContext(DbContextOptions<ReservationsDbContext> options):DbContext(options){public DbSet<ReservableArea> Areas=>Set<ReservableArea>();public DbSet<Reservation> Reservations=>Set<Reservation>();protected override void OnModelCreating(ModelBuilder modelBuilder)=>modelBuilder.ApplyConfigurationsFromAssembly(typeof(ReservationsDbContext).Assembly);}
internal sealed class EfReservationsRepository(ReservationsDbContext db):IReservationsRepository{public async Task AddAsync<T>(T entity,CancellationToken ct) where T:class=>await db.Set<T>().AddAsync(entity,ct);public Task<ReservableArea?> GetAreaAsync(Guid id,CancellationToken ct)=>db.Areas.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<Reservation?> GetReservationAsync(Guid id,CancellationToken ct)=>db.Reservations.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<bool> AreaCodeExistsAsync(Guid communityId,string code,CancellationToken ct)=>db.Areas.AnyAsync(x=>x.CommunityId==communityId&&x.Code==code,ct);public Task<bool> HasOverlapAsync(Guid areaId,DateTimeOffset startsAt,DateTimeOffset endsAt,CancellationToken ct)=>db.Reservations.AnyAsync(x=>x.AreaId==areaId&&x.Status!=ReservationStatus.Cancelled&&x.StartsAt<endsAt&&x.EndsAt>startsAt,ct);public Task SaveChangesAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);}
internal static class ReservationMap{public static void Apply<T>(EntityTypeBuilder<T>b,string table) where T:AppCondominio.SharedKernel.AggregateRoot{b.ToTable(table,"reservations");b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Ignore(x=>x.DomainEvents);}}
internal sealed class AreaConfig:IEntityTypeConfiguration<ReservableArea>{public void Configure(EntityTypeBuilder<ReservableArea>b){ReservationMap.Apply(b,"Areas");b.Property(x=>x.Code).HasMaxLength(60).IsRequired();b.Property(x=>x.Name).HasMaxLength(200).IsRequired();b.Property(x=>x.Fee).HasPrecision(18,2);b.HasIndex(x=>new{x.CommunityId,x.Code}).IsUnique();}}
internal sealed class ReservationConfig:IEntityTypeConfiguration<Reservation>{public void Configure(EntityTypeBuilder<Reservation>b){ReservationMap.Apply(b,"Reservations");b.Property(x=>x.Fee).HasPrecision(18,2);b.Property(x=>x.DecisionBy).HasMaxLength(200);b.HasIndex(x=>new{x.AreaId,x.StartsAt,x.EndsAt});b.HasIndex(x=>new{x.CommunityId,x.RequesterId});}}
public static class DependencyInjection{public static IServiceCollection AddReservationsModule(this IServiceCollection services,IConfiguration configuration){var cs=configuration.GetConnectionString("Reservations")??configuration.GetConnectionString("Maintenance")??configuration.GetConnectionString("Organizations")??throw new InvalidOperationException("Reservations connection string is required.");services.AddDbContext<ReservationsDbContext>(o=>o.UseSqlServer(cs,sql=>sql.MigrationsHistoryTable("__EFMigrationsHistory","reservations")));services.AddScoped<IReservationsRepository,EfReservationsRepository>();services.AddScoped<ReservationService>();return services;}}