using AppCondominio.Modules.Maintenance.Domain;
namespace AppCondominio.Modules.Maintenance.Application;
public interface IMaintenanceRepository
{
 Task AddAsync<T>(T entity,CancellationToken ct) where T:class;
 Task<MaintenanceAsset?> GetAssetAsync(Guid id,CancellationToken ct); Task<PreventivePlan?> GetPlanAsync(Guid id,CancellationToken ct); Task<MaintenanceIncident?> GetIncidentAsync(Guid id,CancellationToken ct); Task<WorkOrder?> GetWorkOrderAsync(Guid id,CancellationToken ct);
 Task<bool> AssetCodeExistsAsync(Guid communityId,string code,CancellationToken ct); Task<bool> WorkOrderNumberExistsAsync(Guid communityId,string number,CancellationToken ct);
 Task<MaintenanceKpi> GetKpiAsync(Guid communityId,DateOnly today,CancellationToken ct); Task SaveChangesAsync(CancellationToken ct);
}
public sealed class MaintenanceService(IMaintenanceRepository repository)
{
 public async Task<Guid> CreateAssetAsync(Guid communityId,string code,string name,string category,string location,CancellationToken ct){if(await repository.AssetCodeExistsAsync(communityId,code,ct))throw new InvalidOperationException("Asset code already exists.");var x=MaintenanceAsset.Create(communityId,code,name,category,location);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
 public async Task<Guid> CreatePreventivePlanAsync(Guid assetId,string name,int frequencyDays,DateOnly nextDueDate,CancellationToken ct){var asset=await repository.GetAssetAsync(assetId,ct)??throw new KeyNotFoundException("Asset not found.");if(asset.Status!=AssetStatus.Active)throw new InvalidOperationException("Preventive plan requires active asset.");var x=PreventivePlan.Create(asset.CommunityId,asset.Id,name,frequencyDays,nextDueDate);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
 public async Task<Guid> ReportIncidentAsync(Guid communityId,Guid? assetId,string title,string description,string priority,string reportedBy,CancellationToken ct){if(assetId.HasValue){var asset=await repository.GetAssetAsync(assetId.Value,ct)??throw new KeyNotFoundException("Asset not found.");if(asset.CommunityId!=communityId)throw new InvalidOperationException("Asset belongs to another community.");}var x=MaintenanceIncident.Create(communityId,assetId,title,description,priority,reportedBy);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
 public async Task<Guid> CreateWorkOrderAsync(Guid communityId,Guid? assetId,Guid? incidentId,Guid? planId,string number,string title,CancellationToken ct){if(await repository.WorkOrderNumberExistsAsync(communityId,number,ct))throw new InvalidOperationException("Work order number already exists.");if(assetId.HasValue&&(await repository.GetAssetAsync(assetId.Value,ct))?.CommunityId!=communityId)throw new InvalidOperationException("Invalid asset for community.");if(incidentId.HasValue&&(await repository.GetIncidentAsync(incidentId.Value,ct))?.CommunityId!=communityId)throw new InvalidOperationException("Invalid incident for community.");if(planId.HasValue&&(await repository.GetPlanAsync(planId.Value,ct))?.CommunityId!=communityId)throw new InvalidOperationException("Invalid preventive plan for community.");var x=WorkOrder.Create(communityId,assetId,incidentId,planId,number,title);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
 public async Task AssignAsync(Guid id,string to,CancellationToken ct){var x=await repository.GetWorkOrderAsync(id,ct)??throw new KeyNotFoundException("Work order not found.");x.Assign(to);await repository.SaveChangesAsync(ct);} public async Task StartAsync(Guid id,CancellationToken ct){var x=await repository.GetWorkOrderAsync(id,ct)??throw new KeyNotFoundException("Work order not found.");x.Start();if(x.IncidentId.HasValue){var i=await repository.GetIncidentAsync(x.IncidentId.Value,ct);if(i?.Status==IncidentStatus.Open)i.Start();}await repository.SaveChangesAsync(ct);}
 public async Task CompleteAsync(Guid id,decimal actualCost,string? procurementReference,DateOnly completedOn,CancellationToken ct){var x=await repository.GetWorkOrderAsync(id,ct)??throw new KeyNotFoundException("Work order not found.");x.Complete(actualCost,procurementReference);if(x.IncidentId.HasValue){var i=await repository.GetIncidentAsync(x.IncidentId.Value,ct);if(i is not null&&i.Status is IncidentStatus.Open or IncidentStatus.InProgress)i.Resolve();}if(x.PreventivePlanId.HasValue){var p=await repository.GetPlanAsync(x.PreventivePlanId.Value,ct);p?.MarkExecuted(completedOn);}await repository.SaveChangesAsync(ct);}
 public Task<MaintenanceKpi> GetKpiAsync(Guid communityId,DateOnly today,CancellationToken ct)=>repository.GetKpiAsync(communityId,today,ct);
}