<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="..\..\People\People.Application\People.Application.csproj" /><ProjectReference Include="..\..\Properties\Properties.Application\Properties.Application.csproj" /><ProjectReference Include="..\..\Billing\Billing.Application\Billing.Application.csproj" /><ProjectReference Include="..\..\Collections\Collections.Application\Collections.Application.csproj" /><ProjectReference Include="..\..\Reservations\Reservations.Application\Reservations.Application.csproj" /><ProjectReference Include="..\..\SecurityOperations\SecurityOperations.Application\SecurityOperations.Application.csproj" /></ItemGroup></Project>