using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace AppCondominio.Modules.Communities.Infrastructure.Migrations;

[DbContext(typeof(CommunitiesDbContext))]
[Migration("20260908023000_InitialCommunities")]
public partial class InitialCommunities:Migration
{
 protected override void Up(MigrationBuilder m)
 {
  m.EnsureSchema("communities");
  m.CreateTable("Communities","communities",t=>new{Id=t.Column<Guid>("uniqueidentifier",nullable:false),OrganizationId=t.Column<Guid>("uniqueidentifier",nullable:false),Code=t.Column<string>("nvarchar(80)",maxLength:80,nullable:false),Name=t.Column<string>("nvarchar(200)",maxLength:200,nullable:false),TaxId=t.Column<string>("nvarchar(20)",maxLength:20,nullable:true),Address=t.Column<string>("nvarchar(500)",maxLength:500,nullable:false),CommunityType=t.Column<string>("nvarchar(80)",maxLength:80,nullable:true),AdministratorName=t.Column<string>("nvarchar(200)",maxLength:200,nullable:true),PresidentName=t.Column<string>("nvarchar(200)",maxLength:200,nullable:true),Status=t.Column<int>("int",nullable:false)},c=>c.PrimaryKey("PK_Communities",x=>x.Id));
  m.CreateIndex("IX_Communities_OrganizationId_Code","Communities","communities",new[]{"OrganizationId","Code"},unique:true);
  m.CreateTable("TaxSettings","communities",t=>new{Id=t.Column<Guid>("uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>("uniqueidentifier",nullable:false),LegalName=t.Column<string>("nvarchar(250)",maxLength:250,nullable:false),TaxId=t.Column<string>("nvarchar(20)",maxLength:20,nullable:false),Establishment=t.Column<string>("nvarchar(10)",maxLength:10,nullable:false),EmissionPoint=t.Column<string>("nvarchar(10)",maxLength:10,nullable:false),AccountingObligation=t.Column<bool>("bit",nullable:false),SriEnvironment=t.Column<string>("nvarchar(20)",maxLength:20,nullable:false)},c=>c.PrimaryKey("PK_TaxSettings",x=>x.Id));m.CreateIndex("IX_TaxSettings_CommunityId","TaxSettings","communities","CommunityId",unique:true);
  m.CreateTable("StructureNodes","communities",t=>new{Id=t.Column<Guid>("uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>("uniqueidentifier",nullable:false),ParentId=t.Column<Guid>("uniqueidentifier",nullable:true),Type=t.Column<int>("int",nullable:false),Code=t.Column<string>("nvarchar(80)",maxLength:80,nullable:false),Name=t.Column<string>("nvarchar(200)",maxLength:200,nullable:false)},c=>c.PrimaryKey("PK_StructureNodes",x=>x.Id));m.CreateIndex("IX_StructureNodes_CommunityId_Code","StructureNodes","communities",new[]{"CommunityId","Code"},unique:true);m.CreateIndex("IX_StructureNodes_ParentId","StructureNodes","communities","ParentId");
  m.CreateTable("CommonAreas","communities",t=>new{Id=t.Column<Guid>("uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>("uniqueidentifier",nullable:false),Code=t.Column<string>("nvarchar(80)",maxLength:80,nullable:false),Name=t.Column<string>("nvarchar(200)",maxLength:200,nullable:false),IsReservable=t.Column<bool>("bit",nullable:false)},c=>c.PrimaryKey("PK_CommonAreas",x=>x.Id));m.CreateIndex("IX_CommonAreas_CommunityId_Code","CommonAreas","communities",new[]{"CommunityId","Code"},unique:true);
  m.CreateTable("BankAccounts","communities",t=>new{Id=t.Column<Guid>("uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>("uniqueidentifier",nullable:false),Bank=t.Column<string>("nvarchar(160)",maxLength:160,nullable:false),Number=t.Column<string>("nvarchar(80)",maxLength:80,nullable:false),Type=t.Column<int>("int",nullable:false),Currency=t.Column<string>("nvarchar(3)",maxLength:3,nullable:false),Use=t.Column<string>("nvarchar(160)",maxLength:160,nullable:false),AccountingAccount=t.Column<string>("nvarchar(80)",maxLength:80,nullable:true)},c=>c.PrimaryKey("PK_BankAccounts",x=>x.Id));
  m.CreateTable("ChargeSettings","communities",t=>new{Id=t.Column<Guid>("uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>("uniqueidentifier",nullable:false),IssueDay=t.Column<int>("int",nullable:false),DueDay=t.Column<int>("int",nullable:false),InterestRate=t.Column<decimal>("decimal(18,6)",nullable:false),ApplicationOrder=t.Column<string>("nvarchar(300)",maxLength:300,nullable:false),Currency=t.Column<string>("nvarchar(3)",maxLength:3,nullable:false),FiscalYear=t.Column<int>("int",nullable:false)},c=>c.PrimaryKey("PK_ChargeSettings",x=>x.Id));m.CreateIndex("IX_ChargeSettings_CommunityId","ChargeSettings","communities","CommunityId",unique:true);
  m.CreateTable("Authorities","communities",t=>new{Id=t.Column<Guid>("uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>("uniqueidentifier",nullable:false),Role=t.Column<string>("nvarchar(80)",maxLength:80,nullable:false),PersonName=t.Column<string>("nvarchar(200)",maxLength:200,nullable:false),StartsOn=t.Column<DateOnly>("date",nullable:false),EndsOn=t.Column<DateOnly>("date",nullable:true),SupportDocumentReference=t.Column<string>("nvarchar(1000)",maxLength:1000,nullable:true)},c=>c.PrimaryKey("PK_Authorities",x=>x.Id));m.CreateIndex("IX_Authorities_CommunityId_Role_StartsOn","Authorities","communities",new[]{"CommunityId","Role","StartsOn"});
  m.CreateTable("Documents","communities",t=>new{Id=t.Column<Guid>("uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>("uniqueidentifier",nullable:false),DocumentType=t.Column<string>("nvarchar(80)",maxLength:80,nullable:false),Name=t.Column<string>("nvarchar(250)",maxLength:250,nullable:false),ExternalReference=t.Column<string>("nvarchar(1000)",maxLength:1000,nullable:false),RegisteredAtUtc=t.Column<DateTimeOffset>("datetimeoffset",nullable:false)},c=>c.PrimaryKey("PK_Documents",x=>x.Id));m.CreateIndex("IX_Documents_CommunityId","Documents","communities","CommunityId");
 }
 protected override void Down(MigrationBuilder m){foreach(var t in new[]{"Authorities","BankAccounts","ChargeSettings","CommonAreas","Documents","StructureNodes","TaxSettings","Communities"})m.DropTable(t,"communities");}
}
