using AppCondominio.Modules.Communities.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace AppCondominio.Modules.Communities.Infrastructure.Migrations;

[DbContext(typeof(CommunitiesDbContext))]
partial class CommunitiesDbContextModelSnapshot:ModelSnapshot
{
 protected override void BuildModel(ModelBuilder m)
 {
#pragma warning disable 612,618
  m.HasAnnotation("ProductVersion","10.0.11").HasAnnotation("Relational:MaxIdentifierLength",128);
  m.Entity<Community>(b=>{b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");b.Property<Guid>("OrganizationId").HasColumnType("uniqueidentifier");b.Property<string>("Code").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");b.Property<string>("TaxId").HasMaxLength(20).HasColumnType("nvarchar(20)");b.Property<string>("Address").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");b.Property<string>("CommunityType").HasMaxLength(80).HasColumnType("nvarchar(80)");b.Property<string>("AdministratorName").HasMaxLength(200).HasColumnType("nvarchar(200)");b.Property<string>("PresidentName").HasMaxLength(200).HasColumnType("nvarchar(200)");b.Property<CommunityStatus>("Status").HasColumnType("int");b.HasKey("Id");b.HasIndex("OrganizationId","Code").IsUnique();b.ToTable("Communities","communities");});
  m.Entity<TaxSettings>(b=>{b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");b.Property<Guid>("CommunityId").HasColumnType("uniqueidentifier");b.Property<string>("LegalName").IsRequired().HasMaxLength(250).HasColumnType("nvarchar(250)");b.Property<string>("TaxId").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");b.Property<string>("Establishment").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");b.Property<string>("EmissionPoint").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");b.Property<bool>("AccountingObligation").HasColumnType("bit");b.Property<string>("SriEnvironment").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");b.HasKey("Id");b.HasIndex("CommunityId").IsUnique();b.ToTable("TaxSettings","communities");});
  m.Entity<StructureNode>(b=>{b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");b.Property<Guid>("CommunityId").HasColumnType("uniqueidentifier");b.Property<Guid?>("ParentId").HasColumnType("uniqueidentifier");b.Property<StructureNodeType>("Type").HasColumnType("int");b.Property<string>("Code").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");b.HasKey("Id");b.HasIndex("CommunityId","Code").IsUnique();b.HasIndex("ParentId");b.ToTable("StructureNodes","communities");});
  m.Entity<CommonArea>(b=>{b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");b.Property<Guid>("CommunityId").HasColumnType("uniqueidentifier");b.Property<string>("Code").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");b.Property<bool>("IsReservable").HasColumnType("bit");b.HasKey("Id");b.HasIndex("CommunityId","Code").IsUnique();b.ToTable("CommonAreas","communities");});
  m.Entity<CommunityBankAccount>(b=>{b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");b.Property<Guid>("CommunityId").HasColumnType("uniqueidentifier");b.Property<string>("Bank").IsRequired().HasMaxLength(160).HasColumnType("nvarchar(160)");b.Property<string>("Number").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");b.Property<BankAccountType>("Type").HasColumnType("int");b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("nvarchar(3)");b.Property<string>("Use").IsRequired().HasMaxLength(160).HasColumnType("nvarchar(160)");b.Property<string>("AccountingAccount").HasMaxLength(80).HasColumnType("nvarchar(80)");b.HasKey("Id");b.ToTable("BankAccounts","communities");});
  m.Entity<ChargeSettings>(b=>{b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");b.Property<Guid>("CommunityId").HasColumnType("uniqueidentifier");b.Property<int>("IssueDay").HasColumnType("int");b.Property<int>("DueDay").HasColumnType("int");b.Property<decimal>("InterestRate").HasPrecision(18,6).HasColumnType("decimal(18,6)");b.Property<string>("ApplicationOrder").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("nvarchar(3)");b.Property<int>("FiscalYear").HasColumnType("int");b.HasKey("Id");b.HasIndex("CommunityId").IsUnique();b.ToTable("ChargeSettings","communities");});
  m.Entity<CommunityAuthority>(b=>{b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");b.Property<Guid>("CommunityId").HasColumnType("uniqueidentifier");b.Property<string>("Role").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");b.Property<string>("PersonName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");b.Property<DateOnly>("StartsOn").HasColumnType("date");b.Property<DateOnly?>("EndsOn").HasColumnType("date");b.Property<string>("SupportDocumentReference").HasMaxLength(1000).HasColumnType("nvarchar(1000)");b.HasKey("Id");b.HasIndex("CommunityId","Role","StartsOn");b.ToTable("Authorities","communities");});
  m.Entity<CommunityDocument>(b=>{b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");b.Property<Guid>("CommunityId").HasColumnType("uniqueidentifier");b.Property<string>("DocumentType").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");b.Property<string>("Name").IsRequired().HasMaxLength(250).HasColumnType("nvarchar(250)");b.Property<string>("ExternalReference").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");b.Property<DateTimeOffset>("RegisteredAtUtc").HasColumnType("datetimeoffset");b.HasKey("Id");b.HasIndex("CommunityId");b.ToTable("Documents","communities");});
#pragma warning restore 612,618
 }
}
