import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { API_BASE_URL } from '../../core/config/api.config';

interface ResidentHomeUnit { communityId:string; unitId:string; personId:string; displayName:string; unitCode:string; location:string; mainAreaM2:number; role:number; accessExpiresAtUtc?:string|null; }
interface ReservableArea { id:string; code:string; name:string; capacity:number; fee:number; }
interface ReceivableRow { dueOn:string; originalAmount:number; outstandingAmount:number; status:number; }

@Component({
  selector: 'app-resident-portal', standalone: true, imports: [CommonModule, FormsModule],
  template: `
    <section class="resident-hero"><div><span class="eyebrow">Mi comunidad</span><h2>Hola{{ residentName ? ', ' + residentName : '' }}</h2><p>Consulta tu estado de cuenta, reserva áreas comunales y autoriza visitas con el acceso asociado a tu usuario.</p></div><span class="resident-security">Acceso validado por PortalCorporativo</span></section>
    <div class="notice error" *ngIf="error">{{ error }}</div><div class="notice success" *ngIf="message">{{ message }}</div>

    <section class="panel" *ngIf="units.length"><div class="panel-title"><h3>Mis unidades</h3><span class="badge">{{ units.length }}</span></div><div class="resident-unit-grid">
      <button type="button" class="resident-unit" *ngFor="let unit of units" [class.selected]="unit.unitId===selectedUnitId" (click)="selectUnit(unit.unitId)"><strong>{{ unit.unitCode }}</strong><span>{{ unit.location }}</span><small>{{ unit.mainAreaM2 }} m² · {{ roleLabel(unit.role) }}</small></button>
    </div></section>

    <section class="metric-grid" *ngIf="selectedUnit"><article class="metric"><span>Saldo pendiente</span><strong>{{ outstandingTotal | currency:'USD':'symbol':'1.2-2' }}</strong></article><article class="metric"><span>Obligaciones abiertas</span><strong>{{ receivables.length }}</strong></article><article class="metric"><span>Estado</span><strong class="resident-status">Activo</strong></article><article class="metric"><span>Unidad</span><strong class="resident-unit-code">{{ selectedUnit.unitCode }}</strong></article></section>

    <section class="panel" *ngIf="selectedUnitId"><div class="panel-title"><h3>Estado de cuenta</h3><button type="button" class="button secondary" (click)="loadStatement()" [disabled]="busy">Actualizar</button></div><div class="table-wrap" *ngIf="receivables.length; else noReceivables"><table><thead><tr><th>Vencimiento</th><th>Original</th><th>Pendiente</th><th>Estado</th></tr></thead><tbody><tr *ngFor="let row of receivables"><td>{{ row.dueOn }}</td><td>{{ row.originalAmount | currency:'USD' }}</td><td>{{ row.outstandingAmount | currency:'USD' }}</td><td>{{ receivableStatus(row.status) }}</td></tr></tbody></table></div><ng-template #noReceivables><p class="empty-state">No hay obligaciones pendientes para esta unidad.</p></ng-template></section>

    <div class="resident-action-grid" *ngIf="selectedUnitId">
      <section class="panel"><h3>Reservar área comunal</h3><form class="form-grid" (ngSubmit)="requestReservation()"><label class="wide">Área<select name="areaId" [(ngModel)]="reservation.areaId" required><option value="" disabled>Seleccione un área</option><option *ngFor="let area of areas" [value]="area.id">{{ area.name }} · Cap. {{ area.capacity }} · {{ area.fee | currency:'USD' }}</option></select></label><label>Desde<input type="datetime-local" name="startsAt" [(ngModel)]="reservation.startsAt" required></label><label>Hasta<input type="datetime-local" name="endsAt" [(ngModel)]="reservation.endsAt" required></label><label>Invitados<input type="number" min="1" step="1" [max]="selectedArea?.capacity || 999" name="guests" [(ngModel)]="reservation.guests" required></label><div class="form-actions"><button class="button primary" [disabled]="busy || !canRequestReservation">Solicitar reserva</button></div></form><p class="empty-state" *ngIf="!areas.length">No hay áreas reservables habilitadas en esta comunidad.</p></section>
      <section class="panel"><h3>Autorizar visita</h3><form class="form-grid" (ngSubmit)="authorizeVisit()"><label>Visitante<input name="visitorName" [(ngModel)]="visit.visitorName" required></label><label>Documento<input name="document" [(ngModel)]="visit.document" required></label><label class="wide">Destino<input name="destination" [(ngModel)]="visit.destination" required></label><label>Válido desde<input type="datetime-local" name="validFrom" [(ngModel)]="visit.validFrom" required></label><label>Válido hasta<input type="datetime-local" name="validTo" [(ngModel)]="visit.validTo" required></label><div class="form-actions"><button class="button primary" [disabled]="busy || !canAuthorizeVisit">Autorizar visita</button></div></form></section>
    </div>`,
  styles:[`.resident-hero{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:24px}.resident-hero h2{font-size:34px;margin:4px 0 6px}.resident-hero p{margin:0;color:#746b7d;max-width:680px}.resident-security{background:#eaf7ef;color:#206c3b;border:1px solid #c9e8d4;border-radius:999px;padding:8px 12px;font-size:12px;font-weight:700}.resident-unit-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px}.resident-unit{border:1px solid #ddd3e5;background:#fff;border-radius:12px;padding:15px;text-align:left;cursor:pointer;display:grid;gap:4px}.resident-unit.selected{border-color:#6d3d91;box-shadow:0 0 0 2px #eadcf4}.resident-unit span,.resident-unit small{color:#746b7d}.resident-action-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.resident-status{font-size:22px!important;color:#237a43}.resident-unit-code{font-size:22px!important}@media(max-width:850px){.resident-hero{flex-direction:column}.resident-action-grid{grid-template-columns:1fr}}`]
})
export class ResidentPortalComponent implements OnInit {
  private readonly http=inject(HttpClient); units:ResidentHomeUnit[]=[]; areas:ReservableArea[]=[]; selectedUnitId=''; receivables:ReceivableRow[]=[]; busy=false; error=''; message=''; reservation={areaId:'',startsAt:'',endsAt:'',guests:1}; visit={visitorName:'',document:'',destination:'',validFrom:'',validTo:''};
  get residentName(){return this.units[0]?.displayName??'';} get selectedUnit(){return this.units.find(x=>x.unitId===this.selectedUnitId);} get selectedArea(){return this.areas.find(x=>x.id===this.reservation.areaId);} get outstandingTotal(){return this.receivables.reduce((s,r)=>s+Number(r.outstandingAmount||0),0);}
  get canRequestReservation(){const area=this.selectedArea;if(!this.selectedUnitId||!area)return false;const start=new Date(this.reservation.startsAt);const end=new Date(this.reservation.endsAt);return !Number.isNaN(start.getTime())&&!Number.isNaN(end.getTime())&&end>start&&Number.isInteger(this.reservation.guests)&&this.reservation.guests>=1&&this.reservation.guests<=area.capacity;} get canAuthorizeVisit(){const start=new Date(this.visit.validFrom);const end=new Date(this.visit.validTo);return !!this.selectedUnitId&&this.visit.visitorName.trim().length>0&&this.visit.document.trim().length>0&&this.visit.destination.trim().length>0&&!Number.isNaN(start.getTime())&&!Number.isNaN(end.getTime())&&end>start;}
  ngOnInit(){this.loadHome();}
  loadHome(){this.busy=true;this.error='';this.http.get<ResidentHomeUnit[]>(`${API_BASE_URL}/resident/home`).subscribe({next:rows=>{this.busy=false;this.units=rows;if(rows.length)this.selectUnit(rows[0].unitId);},error:e=>{this.busy=false;this.error=this.errorMessage(e?.status);}});}
  selectUnit(unitId:string){this.selectedUnitId=unitId;this.reservation.areaId='';this.loadStatement();this.loadAreas();}
  loadStatement(){if(!this.selectedUnitId)return;this.busy=true;this.http.get<{receivables:ReceivableRow[]}>(`${API_BASE_URL}/resident/units/${this.selectedUnitId}/statement`).subscribe({next:r=>{this.busy=false;this.receivables=r.receivables??[];},error:e=>{this.busy=false;this.error=this.errorMessage(e?.status);}});}
  loadAreas(){if(!this.selectedUnitId)return;this.http.get<ReservableArea[]>(`${API_BASE_URL}/resident/units/${this.selectedUnitId}/areas`).subscribe({next:r=>this.areas=r,error:e=>this.error=this.errorMessage(e?.status)});}
  requestReservation(){if(!this.canRequestReservation)return;this.run(this.http.post(`${API_BASE_URL}/resident/units/${this.selectedUnitId}/reservations`,{areaId:this.reservation.areaId,startsAt:new Date(this.reservation.startsAt).toISOString(),endsAt:new Date(this.reservation.endsAt).toISOString(),guests:this.reservation.guests}),'Reserva solicitada correctamente.',()=>this.reservation={areaId:'',startsAt:'',endsAt:'',guests:1});}
  authorizeVisit(){if(!this.canAuthorizeVisit)return;this.run(this.http.post(`${API_BASE_URL}/resident/units/${this.selectedUnitId}/visits`,{visitorName:this.visit.visitorName.trim(),document:this.visit.document.trim(),destination:this.visit.destination.trim(),validFrom:new Date(this.visit.validFrom).toISOString(),validTo:new Date(this.visit.validTo).toISOString()}),'Visita autorizada correctamente.',()=>this.visit={visitorName:'',document:'',destination:'',validFrom:'',validTo:''});}
  private run(request:ReturnType<HttpClient['post']>,success:string,onSuccess?:()=>void){this.busy=true;this.error='';this.message='';request.subscribe({next:()=>{this.busy=false;this.message=success;onSuccess?.();},error:(e:{status?:number})=>{this.busy=false;this.error=this.errorMessage(e.status);}});}
  roleLabel(role:number){return ({1:'Propietario residente',2:'Arrendatario',3:'Familiar',4:'Dependiente',5:'Personal de servicio'} as Record<number,string>)[role]??'Residente';} receivableStatus(status:number){return ({0:'Pendiente',1:'Pago parcial',2:'Pagado',3:'Reversado'} as Record<number,string>)[status]??String(status);} private errorMessage(status?:number){return status===401?'Debe iniciar sesión mediante PortalCorporativo.':status===403?'Su usuario no tiene habilitado el Portal Residente.':'No fue posible completar la operación.';}
}
