using AppCondominio.Modules.Reservations.Domain;
namespace AppCondominio.Modules.Reservations.Application;
public interface IReservationsRepository{Task AddAsync<T>(T entity,CancellationToken ct) where T:class;Task<ReservableArea?> GetAreaAsync(Guid id,CancellationToken ct);Task<Reservation?> GetReservationAsync(Guid id,CancellationToken ct);Task<IReadOnlyCollection<ReservableArea>> ListActiveAreasAsync(Guid communityId,CancellationToken ct);Task<bool> AreaCodeExistsAsync(Guid communityId,string code,CancellationToken ct);Task<bool> HasOverlapAsync(Guid areaId,DateTimeOffset startsAt,DateTimeOffset endsAt,CancellationToken ct);Task SaveChangesAsync(CancellationToken ct);}
public sealed record ReservableAreaSummary(Guid Id,string Code,string Name,int Capacity,decimal Fee);
public sealed class ReservationService(IReservationsRepository repository)
{
 public async Task<Guid> CreateAreaAsync(Guid communityId,string code,string name,int capacity,decimal fee,CancellationToken ct){if(await repository.AreaCodeExistsAsync(communityId,code,ct))throw new InvalidOperationException("Area code already exists.");var x=ReservableArea.Create(communityId,code,name,capacity,fee);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
 public async Task<IReadOnlyCollection<ReservableAreaSummary>> ListActiveAreasAsync(Guid communityId,CancellationToken ct)=>(await repository.ListActiveAreasAsync(communityId,ct)).Select(x=>new ReservableAreaSummary(x.Id,x.Code,x.Name,x.Capacity,x.Fee)).OrderBy(x=>x.Name).ToArray();
 public Task<Guid> RequestAsync(Guid areaId,Guid requesterId,DateTimeOffset startsAt,DateTimeOffset endsAt,int guests,CancellationToken ct)=>RequestCoreAsync(null,areaId,requesterId,startsAt,endsAt,guests,ct);
 public Task<Guid> RequestForCommunityAsync(Guid communityId,Guid areaId,Guid requesterId,DateTimeOffset startsAt,DateTimeOffset endsAt,int guests,CancellationToken ct)=>RequestCoreAsync(communityId,areaId,requesterId,startsAt,endsAt,guests,ct);
 private async Task<Guid> RequestCoreAsync(Guid? expectedCommunityId,Guid areaId,Guid requesterId,DateTimeOffset startsAt,DateTimeOffset endsAt,int guests,CancellationToken ct){var area=await repository.GetAreaAsync(areaId,ct)??throw new KeyNotFoundException("Reservable area not found.");if(expectedCommunityId is not null&&area.CommunityId!=expectedCommunityId.Value)throw new UnauthorizedAccessException("Reservable area does not belong to the authenticated resident community.");if(!area.IsActive)throw new InvalidOperationException("Reservable area is inactive.");if(guests>area.Capacity)throw new InvalidOperationException("Reservation exceeds area capacity.");if(await repository.HasOverlapAsync(areaId,startsAt,endsAt,ct))throw new InvalidOperationException("Reservation overlaps an existing confirmed or pending booking.");var x=Reservation.Create(area.CommunityId,area.Id,requesterId,startsAt,endsAt,guests,area.Fee);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
 public async Task ConfirmAsync(Guid id,string by,CancellationToken ct){var x=await repository.GetReservationAsync(id,ct)??throw new KeyNotFoundException("Reservation not found.");x.Confirm(by);await repository.SaveChangesAsync(ct);} public async Task CancelAsync(Guid id,string by,CancellationToken ct){var x=await repository.GetReservationAsync(id,ct)??throw new KeyNotFoundException("Reservation not found.");x.Cancel(by);await repository.SaveChangesAsync(ct);} public async Task CompleteAsync(Guid id,CancellationToken ct){var x=await repository.GetReservationAsync(id,ct)??throw new KeyNotFoundException("Reservation not found.");x.Complete();await repository.SaveChangesAsync(ct);}
}
