using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace AppCondominio.Modules.Procurement.Infrastructure.Migrations;
[DbContext(typeof(ProcurementDbContext))][Migration("20260908164000_InitialProcurement")]
public partial class InitialProcurement:Migration
{
 protected override void Up(MigrationBuilder m){m.EnsureSchema("procurement");m.CreateTable(name:"Suppliers",schema:"procurement",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),PersonId=t.Column<Guid>(type:"uniqueidentifier",nullable:true),TaxId=t.Column<string>(type:"nvarchar(40)",maxLength:40,nullable:false),LegalName=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),Email=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),IsActive=t.Column<bool>(type:"bit",nullable:false)},constraints:c=>c.PrimaryKey("PK_Suppliers",x=>x.Id));m.CreateIndex(name:"IX_Suppliers_CommunityId_TaxId",schema:"procurement",table:"Suppliers",columns:new[]{"CommunityId","TaxId"},unique:true);
 m.CreateTable(name:"Requisitions",schema:"procurement",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Number=t.Column<string>(type:"nvarchar(60)",maxLength:60,nullable:false),Description=t.Column<string>(type:"nvarchar(800)",maxLength:800,nullable:false),EstimatedAmount=t.Column<decimal>(type:"decimal(18,2)",nullable:false),RequestedBy=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),RequestedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),Status=t.Column<int>(type:"int",nullable:false),ApprovedBy=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:true),ApprovedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:true)},constraints:c=>c.PrimaryKey("PK_Requisitions",x=>x.Id));m.CreateIndex(name:"IX_Requisitions_CommunityId_Number",schema:"procurement",table:"Requisitions",columns:new[]{"CommunityId","Number"},unique:true);
 m.CreateTable(name:"SourcingRounds",schema:"procurement",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),RequisitionId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Title=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),OpenedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),ClosesAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),Status=t.Column<int>(type:"int",nullable:false),AwardedBidId=t.Column<Guid>(type:"uniqueidentifier",nullable:true)},constraints:c=>c.PrimaryKey("PK_SourcingRounds",x=>x.Id));m.CreateIndex(name:"IX_SourcingRounds_RequisitionId",schema:"procurement",table:"SourcingRounds",column:"RequisitionId");
 m.CreateTable(name:"SupplierBids",schema:"procurement",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),SourcingRoundId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),SupplierId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Amount=t.Column<decimal>(type:"decimal(18,2)",nullable:false),DeliveryDays=t.Column<int>(type:"int",nullable:false),ProposalReference=t.Column<string>(type:"nvarchar(500)",maxLength:500,nullable:false),SubmittedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),EvaluationScore=t.Column<decimal>(type:"decimal(5,2)",nullable:true)},constraints:c=>c.PrimaryKey("PK_SupplierBids",x=>x.Id));m.CreateIndex(name:"IX_SupplierBids_SourcingRoundId_SupplierId",schema:"procurement",table:"SupplierBids",columns:new[]{"SourcingRoundId","SupplierId"},unique:true);
 m.CreateTable(name:"PurchaseOrders",schema:"procurement",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),RequisitionId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),SupplierId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),AwardedBidId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Number=t.Column<string>(type:"nvarchar(60)",maxLength:60,nullable:false),Amount=t.Column<decimal>(type:"decimal(18,2)",nullable:false),PayableReference=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),Status=t.Column<int>(type:"int",nullable:false),IssuedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false)},constraints:c=>c.PrimaryKey("PK_PurchaseOrders",x=>x.Id));m.CreateIndex(name:"IX_PurchaseOrders_CommunityId_Number",schema:"procurement",table:"PurchaseOrders",columns:new[]{"CommunityId","Number"},unique:true);m.CreateIndex(name:"IX_PurchaseOrders_AwardedBidId",schema:"procurement",table:"PurchaseOrders",column:"AwardedBidId",unique:true);}
 protected override void Down(MigrationBuilder m){m.DropTable(name:"PurchaseOrders",schema:"procurement");m.DropTable(name:"SupplierBids",schema:"procurement");m.DropTable(name:"SourcingRounds",schema:"procurement");m.DropTable(name:"Requisitions",schema:"procurement");m.DropTable(name:"Suppliers",schema:"procurement");}
}
