import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { API_BASE_URL } from '../../core/config/api.config';
import { CommunityOption, CommunityOptionsService } from '../../core/data/community-options.service';
import { PeopleOptionsService, PersonOption } from '../../core/data/people-options.service';

@Component({selector:'app-security-operations',standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="page-heading"><div><span class="eyebrow">Seguridad</span><h2>Visitas e incidentes</h2><p>Autorizaciones de ingreso, indicadores operativos y habilitación del personal de portería.</p></div></section>
<div class="notice error" *ngIf="error">{{error}}</div><div class="notice success" *ngIf="message">{{message}}</div>
<section class="panel"><h3>Autorizar visita</h3><form class="form-grid" (ngSubmit)="authorizeVisit()">
<label>Comunidad<select [(ngModel)]="visit.communityId" name="communityId" (ngModelChange)="loadPeople($event)" required><option value="">Seleccione una comunidad</option><option *ngFor="let community of communities" [value]="community.id">{{ community.name }} ({{ community.code }})</option></select></label><label>Anfitrión<select [(ngModel)]="visit.hostPersonId" name="hostPersonId" required><option value="">Seleccione una persona</option><option *ngFor="let person of people" [value]="person.id">{{person.displayName}} · {{person.identification}}</option></select></label>
<label>Visitante<input [(ngModel)]="visit.visitorName" name="visitorName" required></label><label>Documento<input [(ngModel)]="visit.document" name="document" required></label>
<label>Destino<input [(ngModel)]="visit.destination" name="destination" required></label><label>Desde<input [(ngModel)]="visit.validFrom" name="validFrom" type="datetime-local" required></label>
<label>Hasta<input [(ngModel)]="visit.validTo" name="validTo" type="datetime-local" required></label><div class="form-actions"><button class="button primary" type="submit" [disabled]="busy">Autorizar visita</button></div></form></section>
<section class="panel"><h3>Acceso de Portería</h3><p>Asigna a un usuario autenticable de PortalCorporativo una única comunidad operativa. La comunidad no es elegible desde la pantalla de portería.</p><form class="form-grid" (ngSubmit)="grantGuardAccess()"><label>Comunidad<select [(ngModel)]="guard.communityId" name="guardCommunityId" required><option value="">Seleccione una comunidad</option><option *ngFor="let community of communities" [value]="community.id">{{ community.name }} ({{ community.code }})</option></select></label><label>Portal User Id<input [(ngModel)]="guard.externalUserId" name="guardExternalUserId" required></label><label>Nombre operativo<input [(ngModel)]="guard.displayName" name="guardDisplayName" required></label><label>Expira<input type="datetime-local" [(ngModel)]="guard.expiresAt" name="guardExpiresAt"></label><div class="form-actions"><button class="button primary" type="submit" [disabled]="busy">Habilitar portería</button></div></form></section>
<section class="panel"><h3>KPI de seguridad</h3><div class="form-grid compact"><label class="wide">Comunidad<select [(ngModel)]="kpiCommunityId" name="kpiCommunityId"><option value="">Seleccione una comunidad</option><option *ngFor="let community of communities" [value]="community.id">{{ community.name }} ({{ community.code }})</option></select></label><div class="form-actions"><button class="button secondary" type="button" (click)="loadKpi()" [disabled]="busy||!kpiCommunityId">Consultar</button></div></div><pre class="result-box" *ngIf="kpi">{{kpi|json}}</pre></section>`})
export class SecurityOperationsComponent implements OnInit{private readonly http=inject(HttpClient);private readonly communityOptions=inject(CommunityOptionsService);private readonly peopleOptions=inject(PeopleOptionsService);communities:CommunityOption[]=[];people:PersonOption[]=[];busy=false;error='';message='';kpi:unknown;kpiCommunityId='';visit={communityId:'',hostPersonId:'',visitorName:'',document:'',destination:'',validFrom:'',validTo:''};guard={communityId:'',externalUserId:'',displayName:'',expiresAt:''};
ngOnInit():void{this.communityOptions.load().subscribe({next:items=>this.communities=items,error:()=>this.error='No se pudieron cargar las comunidades disponibles.'});}
loadPeople(communityId:string):void{this.people=[];this.visit.hostPersonId='';if(!communityId)return;this.peopleOptions.load(communityId).subscribe({next:v=>this.people=v,error:e=>this.error=this.describe(e,'No se pudieron cargar las personas de la comunidad.')});}
authorizeVisit():void{this.busy=true;this.error='';this.message='';const payload={...this.visit,validFrom:new Date(this.visit.validFrom).toISOString(),validTo:new Date(this.visit.validTo).toISOString()};this.http.post<{id:string}>(`${API_BASE_URL}/security-operations/visits`,payload).subscribe({next:v=>{this.busy=false;this.message=`Visita autorizada: ${v.id}`;},error:e=>{this.busy=false;this.error=this.describe(e,'No se pudo autorizar la visita.');}})}
grantGuardAccess():void{this.busy=true;this.error='';this.message='';this.http.post<{id:string}>(`${API_BASE_URL}/security-operations/communities/${this.guard.communityId}/guard-access`,{externalUserId:this.guard.externalUserId,displayName:this.guard.displayName,expiresAtUtc:this.guard.expiresAt?new Date(this.guard.expiresAt).toISOString():null}).subscribe({next:v=>{this.busy=false;this.message=`Acceso de portería creado: ${v.id}`;this.guard={communityId:'',externalUserId:'',displayName:'',expiresAt:''};},error:e=>{this.busy=false;this.error=this.describe(e,'No se pudo habilitar el acceso de portería.');}})}
loadKpi():void{this.busy=true;this.error='';this.kpi=undefined;this.http.get(`${API_BASE_URL}/security-operations/communities/${this.kpiCommunityId}/kpi`).subscribe({next:v=>{this.busy=false;this.kpi=v;},error:e=>{this.busy=false;this.error=this.describe(e,'No se pudo consultar el KPI.');}})}
private describe(e:{status?:number},fallback:string){return e?.status===401?'Sesión requerida desde PortalCorporativo.':e?.status===403?'No tiene permisos requeridos para esta operación.':fallback;}}
