using AppCondominio.Modules.Governance.Application;
using AppCondominio.Modules.Governance.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
namespace AppCondominio.Modules.Governance.Infrastructure;
public sealed class GovernanceDbContext(DbContextOptions<GovernanceDbContext> options):DbContext(options){public DbSet<Assembly> Assemblies=>Set<Assembly>();public DbSet<Motion> Motions=>Set<Motion>();public DbSet<CoexistenceCase> Cases=>Set<CoexistenceCase>();protected override void OnModelCreating(ModelBuilder modelBuilder)=>modelBuilder.ApplyConfigurationsFromAssembly(typeof(GovernanceDbContext).Assembly);}
internal sealed class EfGovernanceRepository(GovernanceDbContext db):IGovernanceRepository{public async Task AddAsync<T>(T entity,CancellationToken ct) where T:class=>await db.Set<T>().AddAsync(entity,ct);public Task<Assembly?> GetAssemblyAsync(Guid id,CancellationToken ct)=>db.Assemblies.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<Motion?> GetMotionAsync(Guid id,CancellationToken ct)=>db.Motions.FirstOrDefaultAsync(x=>x.Id==id,ct);public Task<CoexistenceCase?> GetCaseAsync(Guid id,CancellationToken ct)=>db.Cases.FirstOrDefaultAsync(x=>x.Id==id,ct);public async Task<GovernanceKpi> GetKpiAsync(Guid communityId,CancellationToken ct){var openAssemblies=await db.Assemblies.CountAsync(x=>x.CommunityId==communityId&&x.Status==AssemblyStatus.Open,ct);var approved=await db.Motions.CountAsync(x=>x.CommunityId==communityId&&x.IsClosed&&x.Yes>x.No,ct);var openCases=await db.Cases.CountAsync(x=>x.CommunityId==communityId&&(x.Status==CoexistenceCaseStatus.Reported||x.Status==CoexistenceCaseStatus.UnderReview),ct);var penalties=await db.Cases.Where(x=>x.CommunityId==communityId&&x.Status==CoexistenceCaseStatus.Resolved).SumAsync(x=>(decimal?)x.PenaltyAmount,ct)??0;return new(openAssemblies,approved,openCases,penalties);}public Task SaveChangesAsync(CancellationToken ct)=>db.SaveChangesAsync(ct);}
internal static class GovernanceMap{public static void Apply<T>(EntityTypeBuilder<T>b,string table) where T:AppCondominio.SharedKernel.AggregateRoot{b.ToTable(table,"governance");b.HasKey(x=>x.Id);b.Property(x=>x.Id).ValueGeneratedNever();b.Ignore(x=>x.DomainEvents);}}
internal sealed class AssemblyConfig:IEntityTypeConfiguration<Assembly>{public void Configure(EntityTypeBuilder<Assembly>b){GovernanceMap.Apply(b,"Assemblies");b.Property(x=>x.Title).HasMaxLength(250).IsRequired();b.Property(x=>x.QuorumPercent).HasPrecision(5,2);b.HasIndex(x=>new{x.CommunityId,x.ScheduledAt});}}
internal sealed class MotionConfig:IEntityTypeConfiguration<Motion>{public void Configure(EntityTypeBuilder<Motion>b){GovernanceMap.Apply(b,"Motions");b.Property(x=>x.Title).HasMaxLength(300).IsRequired();b.Ignore(x=>x.IsApproved);b.HasIndex(x=>x.AssemblyId);}}
internal sealed class CaseConfig:IEntityTypeConfiguration<CoexistenceCase>{public void Configure(EntityTypeBuilder<CoexistenceCase>b){GovernanceMap.Apply(b,"CoexistenceCases");b.Property(x=>x.Category).HasMaxLength(100).IsRequired();b.Property(x=>x.Description).HasMaxLength(1200).IsRequired();b.Property(x=>x.ReportedBy).HasMaxLength(200).IsRequired();b.Property(x=>x.Resolution).HasMaxLength(1200);b.Property(x=>x.PenaltyAmount).HasPrecision(18,2);b.Property(x=>x.BillingReference).HasMaxLength(200);b.HasIndex(x=>new{x.CommunityId,x.Status});}}
public static class DependencyInjection{public static IServiceCollection AddGovernanceModule(this IServiceCollection services,IConfiguration configuration){var cs=configuration.GetConnectionString("Governance")??configuration.GetConnectionString("Reservations")??configuration.GetConnectionString("Organizations")??throw new InvalidOperationException("Governance connection string is required.");services.AddDbContext<GovernanceDbContext>(o=>o.UseSqlServer(cs,sql=>sql.MigrationsHistoryTable("__EFMigrationsHistory","governance")));services.AddScoped<IGovernanceRepository,EfGovernanceRepository>();services.AddScoped<GovernanceService>();return services;}}