<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Testcontainers.MsSql" />
    <ProjectReference Include="..\..\src\AppCondominio.Api\AppCondominio.Api.csproj" />
    <ProjectReference Include="..\..\src\AppCondominio.Contracts\AppCondominio.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Organizations\Organizations.Infrastructure\Organizations.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Communities\Communities.Infrastructure\Communities.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Properties\Properties.Infrastructure\Properties.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\People\People.Infrastructure\People.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Billing\Billing.Infrastructure\Billing.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Collections\Collections.Infrastructure\Collections.Infrastructure.csproj" />
  </ItemGroup>
</Project>
