using AppCondominio.Modules.Maintenance.Application;using AppCondominio.Modules.Maintenance.Infrastructure;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.Configuration;using Microsoft.Extensions.DependencyInjection;using Testcontainers.MsSql;
namespace AppCondominio.IntegrationTests;
public sealed class MaintenancePersistenceTests:IAsyncLifetime
{
 private readonly MsSqlContainer _sql=new MsSqlBuilder("mcr.microsoft.com/mssql/server:2022-latest").Build();public Task InitializeAsync()=>_sql.StartAsync();public Task DisposeAsync()=>_sql.DisposeAsync().AsTask();
 [Fact] public async Task Sprint15_runs_asset_plan_incident_work_order_and_kpi(){IConfiguration c=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"ConnectionStrings:Maintenance",_sql.GetConnectionString()}}).Build();var services=new ServiceCollection();services.AddMaintenanceModule(c);await using var p=services.BuildServiceProvider();await using(var s=p.CreateAsyncScope()){await s.ServiceProvider.GetRequiredService<MaintenanceDbContext>().Database.MigrateAsync();}
 var community=Guid.NewGuid();await using(var scope=p.CreateAsyncScope()){var svc=scope.ServiceProvider.GetRequiredService<MaintenanceService>();var asset=await svc.CreateAssetAsync(community,"AST-001","Elevator","Vertical transport","Tower A",default);var plan=await svc.CreatePreventivePlanAsync(asset,"Quarterly service",90,new DateOnly(2026,9,8),default);var incident=await svc.ReportIncidentAsync(community,asset,"Door fault","Door does not close","High","resident",default);var wo=await svc.CreateWorkOrderAsync(community,asset,incident,plan,"WO-001","Repair and preventive service",default);await svc.AssignAsync(wo,"technician",default);await svc.StartAsync(wo,default);await svc.CompleteAsync(wo,250,"PO-001",new DateOnly(2026,9,8),default);var kpi=await svc.GetKpiAsync(community,new DateOnly(2026,9,8),default);Assert.Equal(1,kpi.ActiveAssets);Assert.Equal(0,kpi.OpenIncidents);Assert.Equal(0,kpi.DuePreventivePlans);Assert.Equal(0,kpi.OpenWorkOrders);Assert.Equal(250,kpi.CompletedWorkCost);}
 await using(var scope=p.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<MaintenanceDbContext>();Assert.Single(await db.Assets.ToArrayAsync());Assert.Single(await db.WorkOrders.Where(x=>x.ActualCost==250).ToArrayAsync());}}
}
