using AppCondominio.Modules.Procurement.Application;using AppCondominio.Modules.Procurement.Infrastructure;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.Configuration;using Microsoft.Extensions.DependencyInjection;using Testcontainers.MsSql;
namespace AppCondominio.IntegrationTests;
public sealed class ProcurementPersistenceTests:IAsyncLifetime
{
 private readonly MsSqlContainer _sql=new MsSqlBuilder("mcr.microsoft.com/mssql/server:2022-latest").Build();public Task InitializeAsync()=>_sql.StartAsync();public Task DisposeAsync()=>_sql.DisposeAsync().AsTask();
 [Fact] public async Task Sprint14_runs_requisition_bid_ranking_and_award(){IConfiguration c=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"ConnectionStrings:Procurement",_sql.GetConnectionString()}}).Build();var services=new ServiceCollection();services.AddProcurementModule(c);await using var p=services.BuildServiceProvider();await using(var s=p.CreateAsyncScope()){await s.ServiceProvider.GetRequiredService<ProcurementDbContext>().Database.MigrateAsync();}
 var community=Guid.NewGuid();Guid req,round,bid1,bid2;await using(var scope=p.CreateAsyncScope()){var svc=scope.ServiceProvider.GetRequiredService<ProcurementService>();var sup1=await svc.CreateSupplierAsync(community,null,"RUC1","Supplier 1","a@a.com",default);var sup2=await svc.CreateSupplierAsync(community,null,"RUC2","Supplier 2","b@b.com",default);req=await svc.CreateRequisitionAsync(community,"REQ-001","Elevator maintenance",2000,"admin",default);await svc.ApproveRequisitionAsync(req,"manager",default);round=await svc.OpenRoundAsync(req,"Round 1",DateTimeOffset.UtcNow.AddDays(2),default);bid1=await svc.SubmitBidAsync(round,sup1,1800,5,"proposal-1",default);bid2=await svc.SubmitBidAsync(round,sup2,1750,7,"proposal-2",default);await svc.ScoreBidAsync(bid1,90,default);await svc.ScoreBidAsync(bid2,85,default);var ranking=await svc.GetRankingAsync(round,default);Assert.Equal(bid1,ranking[0].BidId);await svc.CloseRoundAsync(round,default);var order=await svc.AwardAsync(round,bid1,"PO-001","procurement:PO-001",default);Assert.NotEqual(Guid.Empty,order);}
 await using(var scope=p.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<ProcurementDbContext>();Assert.Equal(2,await db.Suppliers.CountAsync());Assert.Equal(2,await db.Bids.CountAsync());Assert.Single(await db.Orders.ToArrayAsync());}}
}
