using AppCondominio.Modules.Procurement.Application;using AppCondominio.Modules.Procurement.Infrastructure;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.Configuration;using Microsoft.Extensions.DependencyInjection;using Testcontainers.MsSql;
namespace AppCondominio.IntegrationTests;
public sealed class ProcurementPersistenceTests:IAsyncLifetime
{
 private readonly MsSqlContainer _sql=new MsSqlBuilder("mcr.microsoft.com/mssql/server:2022-latest").Build();public Task InitializeAsync()=>_sql.StartAsync();public Task DisposeAsync()=>_sql.DisposeAsync().AsTask();
 private ServiceProvider BuildProvider(){IConfiguration c=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"ConnectionStrings:Procurement",_sql.GetConnectionString()}}).Build();var services=new ServiceCollection();services.AddProcurementModule(c);return services.BuildServiceProvider();}
 private static async Task MigrateAsync(ServiceProvider p){await using var s=p.CreateAsyncScope();await s.ServiceProvider.GetRequiredService<ProcurementDbContext>().Database.MigrateAsync();}
 [Fact] public async Task Sprint14_runs_requisition_bid_ranking_and_award(){await using var p=BuildProvider();await MigrateAsync(p);var community=Guid.NewGuid();Guid req,round,bid1,bid2;await using(var scope=p.CreateAsyncScope()){var svc=scope.ServiceProvider.GetRequiredService<ProcurementService>();var sup1=await svc.CreateSupplierAsync(community,null,"RUC1","Supplier 1","a@a.com",default);var sup2=await svc.CreateSupplierAsync(community,null,"RUC2","Supplier 2","b@b.com",default);req=await svc.CreateRequisitionAsync(community,"REQ-001","Elevator maintenance",2000,"admin",default);await svc.ApproveRequisitionAsync(req,"manager",default);round=await svc.OpenRoundAsync(req,"Round 1",DateTimeOffset.UtcNow.AddDays(2),default);bid1=await svc.SubmitBidAsync(round,sup1,1800,5,"proposal-1",default);bid2=await svc.SubmitBidAsync(round,sup2,1750,7,"proposal-2",default);await svc.ScoreBidAsync(bid1,90,default);await svc.ScoreBidAsync(bid2,85,default);var ranking=await svc.GetRankingAsync(round,default);Assert.Equal(bid1,ranking[0].BidId);await svc.CloseRoundAsync(round,default);var order=await svc.AwardAsync(round,bid1,"PO-001","procurement:PO-001",default);Assert.NotEqual(Guid.Empty,order);}await using(var scope=p.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<ProcurementDbContext>();Assert.Equal(2,await db.Suppliers.CountAsync());Assert.Equal(2,await db.Bids.CountAsync());Assert.Single(await db.Orders.ToArrayAsync());}}
 [Fact] public async Task Supplier_portal_resolves_only_authenticated_supplier_and_own_data(){await using var p=BuildProvider();await MigrateAsync(p);var communityA=Guid.NewGuid();var communityB=Guid.NewGuid();await using(var scope=p.CreateAsyncScope()){var svc=scope.ServiceProvider.GetRequiredService<ProcurementService>();var supplierA=await svc.CreateSupplierAsync(communityA,null,"RUC-A","Supplier A","a@supplier.com",default);var supplierB=await svc.CreateSupplierAsync(communityB,null,"RUC-B","Supplier B","b@supplier.com",default);await svc.GrantSupplierPortalAccessAsync(supplierA,"portal-supplier-a",DateTimeOffset.UtcNow.AddDays(5),default);var reqA=await svc.CreateRequisitionAsync(communityA,"REQ-A","Community A work",1000,"admin",default);await svc.ApproveRequisitionAsync(reqA,"manager",default);var roundA=await svc.OpenRoundAsync(reqA,"Round A",DateTimeOffset.UtcNow.AddDays(1),default);var reqB=await svc.CreateRequisitionAsync(communityB,"REQ-B","Community B work",2000,"admin",default);await svc.ApproveRequisitionAsync(reqB,"manager",default);var roundB=await svc.OpenRoundAsync(reqB,"Round B",DateTimeOffset.UtcNow.AddDays(1),default);var context=await svc.GetSupplierPortalContextAsync("portal-supplier-a",default);Assert.Equal(supplierA,context.SupplierId);Assert.Equal(communityA,context.CommunityId);var rounds=await svc.GetSupplierOpenRoundsAsync("portal-supplier-a",default);Assert.Single(rounds);Assert.Equal(roundA,rounds[0].Id);await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>svc.SubmitOwnBidAsync("portal-supplier-a",roundB,900,3,"blocked",default));var bid=await svc.SubmitOwnBidAsync("portal-supplier-a",roundA,950,4,"proposal-a",default);Assert.NotEqual(Guid.Empty,bid);var ownBids=await svc.GetOwnBidsAsync("portal-supplier-a",default);Assert.Single(ownBids);Assert.Equal(bid,ownBids[0].Id);await Assert.ThrowsAsync<InvalidOperationException>(()=>svc.GrantSupplierPortalAccessAsync(supplierB,"portal-supplier-a",DateTimeOffset.UtcNow.AddDays(2),default));}await using(var scope=p.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<ProcurementDbContext>();Assert.Single(await db.SupplierAccessGrants.Where(x=>x.ExternalUserId=="portal-supplier-a").ToArrayAsync());Assert.Single(await db.Bids.ToArrayAsync());}}
}