using AppCondominio.Contracts.People;
using AppCondominio.Modules.Reservations.Application;using AppCondominio.Modules.Reservations.Infrastructure;using AppCondominio.Modules.SecurityOperations.Application;using AppCondominio.Modules.SecurityOperations.Infrastructure;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.Configuration;using Microsoft.Extensions.DependencyInjection;using Testcontainers.MsSql;
namespace AppCondominio.IntegrationTests;
public sealed class ReservationsSecurityPersistenceTests:IAsyncLifetime
{
 private readonly MsSqlContainer _sql=new MsSqlBuilder("mcr.microsoft.com/mssql/server:2022-latest").Build();public Task InitializeAsync()=>_sql.StartAsync();public Task DisposeAsync()=>_sql.DisposeAsync().AsTask();
 [Fact] public async Task Sprint16_runs_booking_visit_access_and_security_incident(){IConfiguration c=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"ConnectionStrings:Reservations",_sql.GetConnectionString()},{"ConnectionStrings:SecurityOperations",_sql.GetConnectionString()}}).Build();var services=new ServiceCollection();services.AddSingleton<IPeopleDirectory,ReservationsPermissivePeopleDirectory>();services.AddReservationsModule(c);services.AddSecurityOperationsModule(c);await using var p=services.BuildServiceProvider();await using(var s=p.CreateAsyncScope()){await s.ServiceProvider.GetRequiredService<ReservationsDbContext>().Database.MigrateAsync();await s.ServiceProvider.GetRequiredService<SecurityOperationsDbContext>().Database.MigrateAsync();}
 var community=Guid.NewGuid();await using(var scope=p.CreateAsyncScope()){var reservations=scope.ServiceProvider.GetRequiredService<ReservationService>();var area=await reservations.CreateAreaAsync(community,"BBQ","BBQ Area",10,20,default);var start=DateTimeOffset.UtcNow.AddDays(1);var booking=await reservations.RequestAsync(area,Guid.NewGuid(),start,start.AddHours(2),6,default);await reservations.ConfirmAsync(booking,"admin",default);await Assert.ThrowsAsync<InvalidOperationException>(()=>reservations.RequestAsync(area,Guid.NewGuid(),start.AddMinutes(30),start.AddHours(1),2,default));
 var security=scope.ServiceProvider.GetRequiredService<SecurityOperationsService>();var from=DateTimeOffset.UtcNow.AddMinutes(-5);var visit=await security.AuthorizeVisitAsync(community,Guid.NewGuid(),"Visitor","DOC-1","A-101",from,from.AddHours(2),default);await security.CheckInAsync(visit,DateTimeOffset.UtcNow,"Main",default);var incident=await security.ReportIncidentAsync(community,"Access","Tailgating","Main gate","guard",default);await security.EscalateIncidentAsync(incident,default);var kpi=await security.GetKpiAsync(community,default);Assert.Equal(1,kpi.CheckedInVisitors);Assert.Equal(1,kpi.EscalatedIncidents);await security.CheckOutAsync(visit,DateTimeOffset.UtcNow.AddMinutes(10),default);await security.ResolveIncidentAsync(incident,"Closed",default);}
 await using(var scope=p.CreateAsyncScope()){Assert.Single(await scope.ServiceProvider.GetRequiredService<ReservationsDbContext>().Reservations.ToArrayAsync());Assert.Single(await scope.ServiceProvider.GetRequiredService<SecurityOperationsDbContext>().Visits.ToArrayAsync());}}
}
internal sealed class ReservationsPermissivePeopleDirectory:IPeopleDirectory{public Task<bool> ExistsInCommunityAsync(Guid communityId,Guid personId,CancellationToken cancellationToken=default)=>Task.FromResult(true);}
