using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace AppCondominio.Modules.Maintenance.Infrastructure.Migrations;
[DbContext(typeof(MaintenanceDbContext))][Migration("20260908171000_InitialMaintenance")]
public partial class InitialMaintenance:Migration
{
 protected override void Up(MigrationBuilder m){m.EnsureSchema("maintenance");m.CreateTable(name:"Assets",schema:"maintenance",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Code=t.Column<string>(type:"nvarchar(60)",maxLength:60,nullable:false),Name=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),Category=t.Column<string>(type:"nvarchar(120)",maxLength:120,nullable:false),Location=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),Status=t.Column<int>(type:"int",nullable:false)},constraints:c=>c.PrimaryKey("PK_Assets",x=>x.Id));m.CreateIndex(name:"IX_Assets_CommunityId_Code",schema:"maintenance",table:"Assets",columns:new[]{"CommunityId","Code"},unique:true);
 m.CreateTable(name:"PreventivePlans",schema:"maintenance",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),AssetId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),Name=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),FrequencyDays=t.Column<int>(type:"int",nullable:false),NextDueDate=t.Column<DateOnly>(type:"date",nullable:false),IsActive=t.Column<bool>(type:"bit",nullable:false)},constraints:c=>c.PrimaryKey("PK_PreventivePlans",x=>x.Id));m.CreateIndex(name:"IX_PreventivePlans_CommunityId_AssetId_Name",schema:"maintenance",table:"PreventivePlans",columns:new[]{"CommunityId","AssetId","Name"},unique:true);
 m.CreateTable(name:"Incidents",schema:"maintenance",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),AssetId=t.Column<Guid>(type:"uniqueidentifier",nullable:true),Title=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),Description=t.Column<string>(type:"nvarchar(1000)",maxLength:1000,nullable:false),Priority=t.Column<string>(type:"nvarchar(40)",maxLength:40,nullable:false),ReportedBy=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),ReportedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),Status=t.Column<int>(type:"int",nullable:false)},constraints:c=>c.PrimaryKey("PK_Incidents",x=>x.Id));m.CreateIndex(name:"IX_Incidents_CommunityId_Status",schema:"maintenance",table:"Incidents",columns:new[]{"CommunityId","Status"});
 m.CreateTable(name:"WorkOrders",schema:"maintenance",columns:t=>new{Id=t.Column<Guid>(type:"uniqueidentifier",nullable:false),CommunityId=t.Column<Guid>(type:"uniqueidentifier",nullable:false),AssetId=t.Column<Guid>(type:"uniqueidentifier",nullable:true),IncidentId=t.Column<Guid>(type:"uniqueidentifier",nullable:true),PreventivePlanId=t.Column<Guid>(type:"uniqueidentifier",nullable:true),Number=t.Column<string>(type:"nvarchar(60)",maxLength:60,nullable:false),Title=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:false),Status=t.Column<int>(type:"int",nullable:false),AssignedTo=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:true),ActualCost=t.Column<decimal>(type:"decimal(18,2)",nullable:false),ProcurementReference=t.Column<string>(type:"nvarchar(200)",maxLength:200,nullable:true),CreatedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:false),CompletedAtUtc=t.Column<DateTimeOffset>(type:"datetimeoffset",nullable:true)},constraints:c=>c.PrimaryKey("PK_WorkOrders",x=>x.Id));m.CreateIndex(name:"IX_WorkOrders_CommunityId_Number",schema:"maintenance",table:"WorkOrders",columns:new[]{"CommunityId","Number"},unique:true);}
 protected override void Down(MigrationBuilder m){m.DropTable(name:"WorkOrders",schema:"maintenance");m.DropTable(name:"Incidents",schema:"maintenance");m.DropTable(name:"PreventivePlans",schema:"maintenance");m.DropTable(name:"Assets",schema:"maintenance");}
}