using AppCondominio.Modules.Procurement.Domain;

namespace AppCondominio.Modules.Procurement.Application;

public interface IProcurementRepository
{
    Task AddAsync<T>(T entity,CancellationToken ct) where T:class;
    Task<SupplierProfile?> GetSupplierAsync(Guid id,CancellationToken ct);Task<PurchaseRequisition?> GetRequisitionAsync(Guid id,CancellationToken ct);Task<SourcingRound?> GetRoundAsync(Guid id,CancellationToken ct);Task<SupplierBid?> GetBidAsync(Guid id,CancellationToken ct);Task<PurchaseOrder?> GetOrderAsync(Guid id,CancellationToken ct);
    Task<SupplierAccessGrant?> GetSupplierAccessAsync(Guid id,CancellationToken ct);Task<SupplierAccessGrant?> GetActiveSupplierAccessByExternalUserAsync(string externalUserId,CancellationToken ct);
    Task<bool> SupplierTaxIdExistsAsync(Guid communityId,string taxId,CancellationToken ct);Task<bool> RequisitionNumberExistsAsync(Guid communityId,string number,CancellationToken ct);Task<bool> BidExistsAsync(Guid roundId,Guid supplierId,CancellationToken ct);Task<bool> OrderNumberExistsAsync(Guid communityId,string number,CancellationToken ct);Task<bool> SupplierAccessExistsAsync(Guid supplierId,string externalUserId,CancellationToken ct);
    Task<IReadOnlyList<SupplierBid>> GetBidsAsync(Guid roundId,CancellationToken ct);Task<IReadOnlyList<SourcingRound>> GetOpenRoundsAsync(Guid communityId,CancellationToken ct);Task<IReadOnlyList<SupplierBid>> GetSupplierBidsAsync(Guid supplierId,CancellationToken ct);Task<IReadOnlyList<PurchaseOrder>> GetSupplierOrdersAsync(Guid supplierId,CancellationToken ct);Task SaveChangesAsync(CancellationToken ct);
}

public sealed record BidRankingRow(Guid BidId,Guid SupplierId,decimal Amount,int DeliveryDays,decimal? Score);
public sealed record SupplierPortalContext(Guid SupplierId,Guid CommunityId,string TaxId,string LegalName,string Email);
public sealed record SupplierRoundRow(Guid Id,string Title,DateTimeOffset ClosesAtUtc);
public sealed record SupplierBidRow(Guid Id,Guid RoundId,decimal Amount,int DeliveryDays,string ProposalReference,DateTimeOffset SubmittedAtUtc,decimal? EvaluationScore);
public sealed record SupplierOrderRow(Guid Id,string Number,decimal Amount,string PayableReference,PurchaseOrderStatus Status,DateTimeOffset IssuedAtUtc);

public sealed class ProcurementService(IProcurementRepository repository)
{
    public async Task<Guid> CreateSupplierAsync(Guid communityId,Guid? personId,string taxId,string legalName,string email,CancellationToken ct){if(await repository.SupplierTaxIdExistsAsync(communityId,taxId,ct))throw new InvalidOperationException("Supplier tax id already exists.");var x=SupplierProfile.Create(communityId,personId,taxId,legalName,email);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
    public async Task<Guid> GrantSupplierPortalAccessAsync(Guid supplierId,string externalUserId,DateTimeOffset? expiresAtUtc,CancellationToken ct){var supplier=await repository.GetSupplierAsync(supplierId,ct)??throw new KeyNotFoundException("Supplier not found.");if(!supplier.IsActive)throw new InvalidOperationException("Supplier is inactive.");if(await repository.SupplierAccessExistsAsync(supplierId,externalUserId,ct))throw new InvalidOperationException("Portal user already has active supplier access.");var grant=SupplierAccessGrant.Create(supplier.CommunityId,supplier.Id,externalUserId,DateTimeOffset.UtcNow,expiresAtUtc);await repository.AddAsync(grant,ct);await repository.SaveChangesAsync(ct);return grant.Id;}
    public async Task RevokeSupplierPortalAccessAsync(Guid accessId,string reason,CancellationToken ct){var access=await repository.GetSupplierAccessAsync(accessId,ct)??throw new KeyNotFoundException("Supplier access not found.");access.Revoke(reason);await repository.SaveChangesAsync(ct);}
    public async Task<SupplierPortalContext> GetSupplierPortalContextAsync(string externalUserId,CancellationToken ct){if(string.IsNullOrWhiteSpace(externalUserId))throw new UnauthorizedAccessException("Authenticated Portal user is required.");var access=await repository.GetActiveSupplierAccessByExternalUserAsync(externalUserId.Trim(),ct)??throw new UnauthorizedAccessException("Supplier access was not found for the authenticated user.");if(!access.IsUsable(DateTimeOffset.UtcNow))throw new UnauthorizedAccessException("Supplier access is expired or revoked.");var supplier=await repository.GetSupplierAsync(access.SupplierId,ct)??throw new UnauthorizedAccessException("Supplier profile was not found.");if(!supplier.IsActive||supplier.CommunityId!=access.CommunityId)throw new UnauthorizedAccessException("Supplier profile is not active for this community.");return new(supplier.Id,supplier.CommunityId,supplier.TaxId,supplier.LegalName,supplier.Email);}
    public async Task<IReadOnlyList<SupplierRoundRow>> GetSupplierOpenRoundsAsync(string externalUserId,CancellationToken ct){var current=await GetSupplierPortalContextAsync(externalUserId,ct);return (await repository.GetOpenRoundsAsync(current.CommunityId,ct)).Where(x=>x.ClosesAtUtc>DateTimeOffset.UtcNow).Select(x=>new SupplierRoundRow(x.Id,x.Title,x.ClosesAtUtc)).OrderBy(x=>x.ClosesAtUtc).ToArray();}
    public async Task<IReadOnlyList<SupplierBidRow>> GetOwnBidsAsync(string externalUserId,CancellationToken ct){var current=await GetSupplierPortalContextAsync(externalUserId,ct);return (await repository.GetSupplierBidsAsync(current.SupplierId,ct)).Select(x=>new SupplierBidRow(x.Id,x.SourcingRoundId,x.Amount,x.DeliveryDays,x.ProposalReference,x.SubmittedAtUtc,x.EvaluationScore)).OrderByDescending(x=>x.SubmittedAtUtc).ToArray();}
    public async Task<IReadOnlyList<SupplierOrderRow>> GetOwnOrdersAsync(string externalUserId,CancellationToken ct){var current=await GetSupplierPortalContextAsync(externalUserId,ct);return (await repository.GetSupplierOrdersAsync(current.SupplierId,ct)).Select(x=>new SupplierOrderRow(x.Id,x.Number,x.Amount,x.PayableReference,x.Status,x.IssuedAtUtc)).OrderByDescending(x=>x.IssuedAtUtc).ToArray();}
    public async Task<Guid> SubmitOwnBidAsync(string externalUserId,Guid roundId,decimal amount,int deliveryDays,string proposalReference,CancellationToken ct){var current=await GetSupplierPortalContextAsync(externalUserId,ct);var round=await repository.GetRoundAsync(roundId,ct)??throw new KeyNotFoundException("Sourcing round not found.");if(round.CommunityId!=current.CommunityId)throw new UnauthorizedAccessException("Sourcing round does not belong to the supplier community.");return await SubmitBidAsync(roundId,current.SupplierId,amount,deliveryDays,proposalReference,ct);}
    public async Task AcknowledgeOwnOrderAsync(string externalUserId,Guid orderId,CancellationToken ct){var current=await GetSupplierPortalContextAsync(externalUserId,ct);var order=await repository.GetOrderAsync(orderId,ct)??throw new KeyNotFoundException("Purchase order not found.");if(order.SupplierId!=current.SupplierId||order.CommunityId!=current.CommunityId)throw new UnauthorizedAccessException("Purchase order does not belong to the authenticated supplier.");order.Acknowledge();await repository.SaveChangesAsync(ct);}
    public async Task<Guid> CreateRequisitionAsync(Guid communityId,string number,string description,decimal estimatedAmount,string requestedBy,CancellationToken ct){if(await repository.RequisitionNumberExistsAsync(communityId,number,ct))throw new InvalidOperationException("Requisition number already exists.");var x=PurchaseRequisition.Create(communityId,number,description,estimatedAmount,requestedBy);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
    public async Task ApproveRequisitionAsync(Guid id,string by,CancellationToken ct){var x=await repository.GetRequisitionAsync(id,ct)??throw new KeyNotFoundException("Requisition not found.");x.Approve(by);await repository.SaveChangesAsync(ct);}
    public async Task<Guid> OpenRoundAsync(Guid requisitionId,string title,DateTimeOffset closesAtUtc,CancellationToken ct){var r=await repository.GetRequisitionAsync(requisitionId,ct)??throw new KeyNotFoundException("Requisition not found.");r.StartSourcing();var x=SourcingRound.Create(r.CommunityId,r.Id,title,closesAtUtc);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
    public async Task<Guid> SubmitBidAsync(Guid roundId,Guid supplierId,decimal amount,int deliveryDays,string proposalReference,CancellationToken ct){var round=await repository.GetRoundAsync(roundId,ct)??throw new KeyNotFoundException("Sourcing round not found.");if(round.Status!=SourcingRoundStatus.Open)throw new InvalidOperationException("Sourcing round is not open.");var supplier=await repository.GetSupplierAsync(supplierId,ct)??throw new KeyNotFoundException("Supplier not found.");if(!supplier.IsActive||supplier.CommunityId!=round.CommunityId)throw new InvalidOperationException("Supplier is not eligible for this community.");if(await repository.BidExistsAsync(roundId,supplierId,ct))throw new InvalidOperationException("Supplier already submitted a bid.");var x=SupplierBid.Create(round.CommunityId,roundId,supplierId,amount,deliveryDays,proposalReference);await repository.AddAsync(x,ct);await repository.SaveChangesAsync(ct);return x.Id;}
    public async Task ScoreBidAsync(Guid bidId,decimal score,CancellationToken ct){var b=await repository.GetBidAsync(bidId,ct)??throw new KeyNotFoundException("Bid not found.");b.Score(score);await repository.SaveChangesAsync(ct);}
    public async Task CloseRoundAsync(Guid roundId,CancellationToken ct){var r=await repository.GetRoundAsync(roundId,ct)??throw new KeyNotFoundException("Sourcing round not found.");r.Close();await repository.SaveChangesAsync(ct);}
    public async Task<IReadOnlyList<BidRankingRow>> GetRankingAsync(Guid roundId,CancellationToken ct)=>(await repository.GetBidsAsync(roundId,ct)).OrderByDescending(x=>x.EvaluationScore??-1).ThenBy(x=>x.Amount).Select(x=>new BidRankingRow(x.Id,x.SupplierId,x.Amount,x.DeliveryDays,x.EvaluationScore)).ToArray();
    public async Task<Guid> AwardAsync(Guid roundId,Guid bidId,string orderNumber,string payableReference,CancellationToken ct){var round=await repository.GetRoundAsync(roundId,ct)??throw new KeyNotFoundException("Sourcing round not found.");var bid=await repository.GetBidAsync(bidId,ct)??throw new KeyNotFoundException("Bid not found.");if(bid.SourcingRoundId!=round.Id)throw new InvalidOperationException("Bid does not belong to sourcing round.");if(bid.EvaluationScore is null)throw new InvalidOperationException("Bid must be evaluated before award.");if(await repository.OrderNumberExistsAsync(round.CommunityId,orderNumber,ct))throw new InvalidOperationException("Purchase order number already exists.");var req=await repository.GetRequisitionAsync(round.RequisitionId,ct)??throw new KeyNotFoundException("Requisition not found.");round.Award(bid.Id);req.MarkAwarded();var order=PurchaseOrder.Create(round.CommunityId,req.Id,bid.SupplierId,bid.Id,orderNumber,bid.Amount,payableReference);await repository.AddAsync(order,ct);await repository.SaveChangesAsync(ct);return order.Id;}
    public async Task AcknowledgeOrderAsync(Guid id,CancellationToken ct){var x=await repository.GetOrderAsync(id,ct)??throw new KeyNotFoundException("Purchase order not found.");x.Acknowledge();await repository.SaveChangesAsync(ct);}
    public async Task CompleteOrderAsync(Guid id,CancellationToken ct){var x=await repository.GetOrderAsync(id,ct)??throw new KeyNotFoundException("Purchase order not found.");x.Complete();await repository.SaveChangesAsync(ct);}
}
