using AppCondominio.Contracts.Security;
using AppCondominio.Modules.Treasury.Application;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
namespace AppCondominio.Modules.Treasury.Api;
public static class TreasuryEndpoints
{
 public static IEndpointRouteBuilder MapTreasuryEndpoints(this IEndpointRouteBuilder endpoints){var g=endpoints.MapGroup("/api/treasury").WithTags("Treasury").RequireAuthorization();g.MapPost("/payables",async(CreatePayableRequest r,TreasuryService s,CancellationToken ct)=>Results.Created("/api/treasury/payables",new{id=await s.CreatePayableAsync(r.CommunityId,r.SupplierId,r.DocumentNumber,r.DocumentDate,r.DueDate,r.Amount,r.ExpenseAccount,r.PayableAccount,ct)})).RequireAuthorization(AppCondominioPermissions.Treasury.Manage);g.MapPost("/payables/{payableId:guid}/requests",async(Guid payableId,RequestPaymentRequest r,TreasuryService s,CancellationToken ct)=>Results.Created("/api/treasury/payment-requests",new{id=await s.RequestPaymentAsync(payableId,r.Amount,r.RequestedBy,ct)})).RequireAuthorization(AppCondominioPermissions.Treasury.Manage);g.MapPost("/requests/{id:guid}/approve",async(Guid id,DecisionRequest r,TreasuryService s,CancellationToken ct)=>{await s.ApproveAsync(id,r.By,ct);return Results.NoContent();}).RequireAuthorization(AppCondominioPermissions.Treasury.Manage);g.MapPost("/requests/{id:guid}/reject",async(Guid id,RejectRequest r,TreasuryService s,CancellationToken ct)=>{await s.RejectAsync(id,r.By,r.Reason,ct);return Results.NoContent();}).RequireAuthorization(AppCondominioPermissions.Treasury.Manage);g.MapPost("/requests/{id:guid}/pay",async(Guid id,PayRequest r,TreasuryService s,CancellationToken ct)=>Results.Ok(new{id=await s.PayAsync(id,r.BankAccountId,r.PaymentReference,r.PaidOn,ct)})).RequireAuthorization(AppCondominioPermissions.Treasury.Manage);g.MapPost("/disbursements/{id:guid}/reverse",async(Guid id,TreasuryService s,CancellationToken ct)=>{await s.ReverseAsync(id,ct);return Results.NoContent();}).RequireAuthorization(AppCondominioPermissions.Treasury.Manage);g.MapGet("/communities/{communityId:guid}/cash-forecast",async(Guid communityId,TreasuryService s,CancellationToken ct)=>Results.Ok(await s.ForecastAsync(communityId,ct))).RequireAuthorization(AppCondominioPermissions.Treasury.Read);return endpoints;}
 private sealed record CreatePayableRequest(Guid CommunityId,Guid SupplierId,string DocumentNumber,DateOnly DocumentDate,DateOnly DueDate,decimal Amount,string ExpenseAccount,string PayableAccount);private sealed record RequestPaymentRequest(decimal Amount,string RequestedBy);private sealed record DecisionRequest(string By);private sealed record RejectRequest(string By,string Reason);private sealed record PayRequest(Guid BankAccountId,string PaymentReference,DateOnly PaidOn);
}
